### ISSUE TITLE
설치/사용방법 메뉴얼 갱신 부탁드려요.

### ISSUE THREAD

**Issue by noritersand** [naver/smarteditor2#1]
2.8.2.3 버전과 비교해 구조가 달라진걸로 보입니다만... 
예전 메뉴얼로는 제대로 설치할 수 없어요 ㅠㅠ

**Comment by kyungilpark** [comment]
@noritersand 님
넵 매뉴얼 갱신이 필요한데 시간이 없어서 작업하지 못했습니다. ㅠ.ㅠ
빠른 시일내에 갱신하도록 하겠습니다. 관심 감사드립니다.
