### ISSUE TITLE
복사해 넣은 게시판 글 시작과 끝에 ? 생기는 이슈

### ISSUE THREAD

**Issue by babisco** [naver/smarteditor2#10]
줄간 ? 생겨서 이 오류는 잡았는데
게시한 글을 복사하여 붙여 넣기 했을경우 
붙여넣은 시작과 끝에 &nbsp; ? 이런식으로 (HTML모드로 확인시) 생성되어 저장했을때 ?가 보이는 현상이 발생하고 수정하려고 하면 스크립트 오류가 납니다..혹시 원인 또는 해결방법이 잇을까요?

**Comment by kyungilpark** [comment]
문의주신내용만으로는 어떤 이슈인지 확인이 안됩니다.
사용하신 스마트에디터버전과 재현환경(os및브라우저) 및 재현방법을 적어주시면 확인해보도록 하겠습니다.

**Comment by babisco** [comment]
현재 파일에는 SmartEditor2 2.8.2 사용하고 있으며, 윈도우 10에 IE11을 사용하고 있습니다. 테스트해 본 컴퓨터는 환경이 상이한 경우도 있습니다만 같은 오류가 발생하고있습니다. (게시판 글 작성 후 게시글 복사 새글에서 붙여넣기 또는 수정해서 붙여넣기 한 후 등록하면 ?가 붙여넣기 시작한 부분과 끝에 생성되고 그 글을 수정하려고 하면 스크립트 오류가 발생합니다->smarteditor2.min.js에서 smarteditor2.js로 변경하여도 같은 현상이 일어납니다.) 현재 xplatform을 기반으로 화면에 액티브엑스로 삽입을 하여 사용하고 있습니다.

**Comment by kyungilpark** [comment]
처음 보는 이슈인데다 xplatform기반에 얹어서 사용하신다니 딱히 재현해볼 방법이 없네요.. ㅠ.ㅠ
붙여넣기시 바로 ?가 생기는게 아니라 붙여넣기한 글을 저장하는 경우에 ?가 생긴다는 얘기인가요?
만약 저장시에 ?가 생긴다면 서버나 플랫폼쪽에서 인식하지 못하는 유니코드문자가 잘못 인코딩되어 저장되는 것이 아닌가 싶습니다.
스마트에디터에서 커서위치를 정확하게 고정시키기 위해 특수한 유니코드문자`\uFEFF`를 종종 삽입하는데 이 문자가 아닌가 샆습니다. 저장전에 해당문자를 클린징해보시는건 어떨까 싶습니다.

**Comment by kyungilpark** [comment]
이슈정리차원에서 닫습니다.
