### ISSUE TITLE
스마트 에디터 사진 이슈

### ISSUE THREAD

**Issue by kimgy1027** [naver/smarteditor2#100]
스마트에디터 2.0 사용시 다음과 같은 이슈는 어떤 현상때문에 발생하는건지 여쭤보고 싶습니다.

서버 방화벽과 관계가 있는건지 어떤 사안을 주의해야 하는지 알고싶습니다

에디터(네이버편집기)의 [사진] 눌러서 사진 첨부하면 첨부용 팝업창만 뜨고 사진은 등록 안됨 ('사진첨부하기' 팝업창의 확인버튼 회색으로 비활성화 되어있고, 취소버튼은 눌러도 아무 반응없음)

에디터(네이버편집기)로 사진첨부하면 "[가이드]사진 업로더할 서버URL셋팅이 필요합니다.-onAjaxError" 라고 뜨고 첨부안됨
![onajaxerror](https://user-images.githubusercontent.com/40843051/49915020-f2841900-fed6-11e8-87f1-02dc4ec0a9b8.png)
![default](https://user-images.githubusercontent.com/40843051/49915026-f748cd00-fed6-11e8-811a-b9d61d6d0f8c.png)

**Comment by kyungilpark** [comment]
첨부해주신 alert 은 ajax 로 이미지업로드시 서버응답결과가 200 번이 아닌 경우에 뜨는 오류메시지입니다.
서버응답결과를 확인바랍니다.
