### ISSUE TITLE
스마트에디터2.0 사용중인대 포토업로드 변경된거 적용할수있나요?

### ISSUE THREAD

**Issue by seolkyungmin** [naver/smarteditor2#101]
![c20170209_233433](https://user-images.githubusercontent.com/10863726/50467616-40c10e00-09e7-11e9-85e8-eb8f0ad45d23.png)

현재 밑에버전 사용중입니다

위에버전 사용할수있나요?

사용법좀 부탁드려요
![34234234](https://user-images.githubusercontent.com/10863726/50467650-57fffb80-09e7-11e9-9280-e3a208f38f14.PNG)

**Comment by kyungilpark** [comment]
"네이버 포토업로더"의 경우 네이버로그인 및 포토API연동이 필요하기 때문에 보안 이슈가 있을 수 있어 오픈소스 버전에는 포함되어 있지 않습니다.
사내에서 사용하시는 경우라면 사내메일로 문의부탁드립니다.
