### ISSUE TITLE
스마트 에디터2.0 스프링 사진 업로드

### ISSUE THREAD

**Issue by pupuzel** [naver/smarteditor2#102]
안녕하세요 다름이 아니라 스마트 에디터2.8.2.3 버전 을 사용해서
전자정부 프레임워크 프로젝트에 사용하려고 합니다.

서버쪽에서 MultipartHttpServletRequest 으로 
이미지 파일 multipart/form-data 요청을 받으려고 하는데

구글링을 통해 여러가지 사례들을 보고 해결해보려 했으나 
안되가지고 이렇게 질문 드려봅니다..

attach_photo.js 파일
callAjaxForHTML5 함수에서 

마지막 요청 부분 oAjax.request(tempFile); 을
임의로 var request = new XMLHttpRequest(); 생성해서
요청하면 잘되는데

var oAjax = jindo.$Ajax(sUploadURL, { ....
oAjax 사용하면 MultipartHttpServletRequest 로 받을수가 없더라구요..

스프링으로 스마트에디터 이미지 업로드 어떻게해야하나요?

**Comment by kyungilpark** [comment]
1. 혹시 인터셉터에서 필터링되고 있는건 아닌지 확인부탁드립니다. #13 참고
2. 모든 브라우저에서 안되는건지 특정 브라우저에서만 안되는건지 확인부탁드립니다.
    - 이 경우 jindo 라이브러리 문제일수 있으니 `2.8.2.3` 버전이 아닌 `최신버전(현재 2.9.1)` 에 번들링된 jindo 로 교체 후 확인부탁드립니다.
    - https://github.com/naver/smarteditor2/blob/master/dist/js/lib/jindo2.all.js
3. 이미지업로드는 참고용 샘플파일이기 때문에 꼭 `jindo.$Ajax` 를 사용하지 않으셔도 됩니다.
    - `new XMLHttpRequest()` 를 직접 사용하셔도 됩니다.
