### ISSUE TITLE
혹시 툴바에 셀 넓이 높이 지정할 수 있는 버튼 추가할려면?

### ISSUE THREAD

**Issue by bierson** [naver/smarteditor2#103]
스마트에디터 2 사용중인데요.

툴바에 셀 넓이 높이 지정할 수 있는 버튼 추가할려면 어떻게 해야 하나요?
물론 html에서 해당 셀 찾아서 넓이 조정하면 되겠지만 사용자가 사용하기에는 어려움이 있어서요.

감사합니다.

**Comment by kyungilpark** [comment]
셀 넓이 높이 지정하는 플러그인을 만드시고 툴바마크업수정하시면 됩니다.
[개발자 가이드](http://naver.github.io/smarteditor2/user_guide/) "기능추가및변경하기 > 새로운 기능 추가" 항목 참고바랍니다.
