### ISSUE TITLE
외부 텍스트를 붙여넣기 할 때 <div>에 들어가는데 이 부분을 수정할 수 있는 방법

### ISSUE THREAD

**Issue by miwhahan** [naver/smarteditor2#104]
안녕하세요.
2.3.10버전을 사용중입니다.
외부 텍스트를 복사에서 에디터에 붙여넣을 때 div 태그에 감싸서 들어가는데 이 부분을 수정할 수 있는 방법에 대해 문의드립니다.
여러 줄의 텍스트를 글자 크기 등의 속성을 부여한 span 태그 뒤에 붙여넣을때 <div>에 감싸지면서 id = husky_bookmark_start_ 가 나타나며 뒤의 내용이 사라지는 형상이 발생합니다.

**Comment by kyungilpark** [comment]
붙여넣기시 문단을 분리하여 삽입하는 로직은 코어에 해당하는 부분이라 간단하게 수정할 수 있는 부분이 아닙니다.
최신버전으로 업데이트하시길 권장드립니다.
최신버전 업데이트 후에도 해결이 안된다면 재현브라우저와 재현절차를 좀 더 상세하게 올려주시길 부탁드립니다.
