### ISSUE TITLE
angular에서 사용

### ISSUE THREAD

**Issue by sangminK** [naver/smarteditor2#105]
angular 에서 스마트 에디터 사용할 수 있나요? (angularjs 아님)
버전은 7입니다.

일단 다운받은 스마트에디터 폴더를 앵귤러 프로젝트로 옮기는 것 자체가 안돼서요

**Comment by kyungilpark** [comment]
angular 를 써보지 않아서 어떤식으로 연결하시려는 건지 감이 잘 안오네요...

스마트에디터를 동적으로 삽입하는 래핑컴포넌트를 만드셔야하지 않을까 싶은데요..
stackoverflow 에서 ckeditor 래핑하는 예시 참고하시면 좋을듯합니다.
https://stackoverflow.com/a/41816744

물론 이렇게 쉽진 않을것 같습니다만... ㅠ.ㅠ

**Comment by sangminK** [comment]
그러면요
앵귤러 타입스크립트 파일들이 빌드하면 전부 js 파일로 바뀌는데요
스마트에디터에 필요한 js 파일들은 빌드하고 나서 js 있는 폴더에 넣어야 할까요?

**Comment by kyungilpark** [comment]
스마트에디터는 이미 js 파일이므로 앵귤러 빌드과정에 포함할수는 없고 외부리소스라고 생각하시면 됩니다.
스마트에디터는 `dist` 폴더에 빌드된 파일이 있으니 따로 빌드할 필요없이 리소스폴더에 복사해 넣어시면 됩니다.

앞서 언급한 stackoverflow 와 앵귤러튜토리얼 참고해서 연동 샘플 만들어봤습니다.
https://github.com/kyungilpark/smarteditor2-angular-sample
커밋로그 순서대로 확인하시면 연동한 방법 이해하시는데 도움이 되실듯합니다.

해당 샘플은 앵귤러에서 스마트에디터를 띄울수 있는지 확인하는 목적으로 만든거라서 추가옵션설정이나 데이터로드/저장, 이벤트연동등은 직접 구현하셔야 합니다.

**Comment by sangminK** [comment]
일주일 전에 angular를 써보시지 않으셨다고 했는데
짧은 시간에 샘플을 만드시고 너무 대단하시네요!
정말 감사합니다.

**Comment by kyungilpark** [comment]
아 angular 를 실제 플젝에 사용해본적이 없어서 아키텍쳐를 정확히 이해하고 있진 않습니다.
angular2 처음나올때 스터디한다고 Tour of Heroes 튜토리얼은 따라해본적은 있구요 ㅎㅎ
이슈는 닫겠습니다.
