### ISSUE TITLE
이미지 퀵에디터 

### ISSUE THREAD

**Issue by MJKang9** [naver/smarteditor2#106]
스마트에디터 2.9.1 사용중입니다. 
(#36) 을 참고하여 이미지 퀵에디터를 추가했는데,

드래그를 통해 이미지 크기를 변환할 수 있는 레이어는
(이미지 가장자리 꼭지점에 사각형 포인터가 생기는 것)

IE에서만 가능하던데 Chrome이나 Edge에서 적용할 수 있는 방법이 있을까요?

**Comment by kyungilpark** [comment]
`이미지 가장자리 꼭지점에 사각형 포인터가 생기는 것` 은 IE브라우저 자체에서 제공하는 기능입니다.
다른 브라우저는 별도 플러그인을 만드셔야 할것 같습니다.
