### ISSUE TITLE
스마트에디터 2.0 사용중 크롬애서의 오류

### ISSUE THREAD

**Issue by realmon** [naver/smarteditor2#107]
크롬에서 에디터 불러오는 부분에서 아래와 같은 오류가 납니다.

jindo.min.js:1 Uncaught TypeError: node.getElementsByTagName is not a function
    at getElementsByClass (jindo.min.js:1)
    at getChilds_dontShrink (jindo.min.js:1)
    at fpCompiled (eval at compileParts (jindo.min.js:1), <anonymous>:1:93)
    at jindo.min.js:1
    at old_cssquery (jindo.min.js:1)
    at cssquery (jindo.min.js:1)
    at Function.jindo.$$.jindo.cssquery.cssquery.getSingle (jindo.min.js:1)
    at createSEditor2 (SE2BasicCreator.js:8)
    at HTMLIFrameElement.<anonymous> (HuskyEZCreator.js:77)

익스에선은 정상적으로 나오고 있는걸로 확인되구요.
어떤 부분을 확인 해야 하는지 답변 부탁 드립니다~~~

**Comment by kyungilpark** [comment]
오잉? 진도라이브러리에서 나는 오류라 정확히는 모르겠는데 node 를 잘못찾은거 같습니다.
어떤식으로 적용하셨는지 `html` 과 에디터초기화 코드(`nhn.husky.EZCreator.createInIFrame`) 부분 확인해주실 수 있을까요?

**Comment by realmon** [comment]
에디터 생성은 서버쪽에서 변수 처리합니다.

아래 코드로 전부 공통으로 사용하는데요.
특정 사이트만 크롬에서 적용이 안됩니다.
(다른 사이트들은 정상 작동함)
만든지 오래된 사이트라서 뭔가 설정을 잡아 줘야 하는거 같은데요.
혹시 몰라서 적용안되는 사이트 주소도 올립니다.

jnes.co.kr

				$TextArea = "<script type=\"text/javascript\" src=\"".$EditorPath."/js/HuskyEZCreator.js\"></script>
								<textarea id=\"b_content\" name=\"b_content\" style=\"width:100%;height:300px;display:none;\">".$content."</textarea>
								<script type=\"text/javascript\">
								var oEditors = [];
								
								nhn.husky.EZCreator.createInIFrame({
									oAppRef: oEditors,
									elPlaceHolder: \"b_content\",
									sSkinURI: \"".$EditorPath."/SmartEditor2Skin.html\",	
									htParams : {
										bUseToolbar : true,				// 툴바 사용 여부 (true:사용/ false:사용하지 않음)
										bUseVerticalResizer : true,		// 입력창 크기 조절바 사용 여부 (true:사용/ false:사용하지 않음)
										bUseModeChanger : true,			// 모드 탭(Editor | HTML | TEXT) 사용 여부 (true:사용/ false:사용하지 않음)
										//aAdditionalFontList : aAdditionalFontSet,		// 추가 글꼴 목록
										fOnBeforeUnload : function(){
											//alert(\"완료!\");
										}
									}, //boolean
									fOnAppLoad : function(){
										//예제 코드
										//oEditors.getById[\"b_content\"].exec(\"PASTE_HTML\", [\"로딩이 완료된 후에 본문에 삽입되는 text입니다.\"]);
									},
									fCreator: \"createSEditor2\"
								});
"


nhn.husky.EZCreator = new (function(){
	this.nBlockerCount = 0;

	this.createInIFrame = function(htOptions){
		if(arguments.length == 1){
			var oAppRef = htOptions.oAppRef;
			var elPlaceHolder = htOptions.elPlaceHolder;
			var sSkinURI = htOptions.sSkinURI;
			var fCreator = htOptions.fCreator;
			var fOnAppLoad = htOptions.fOnAppLoad;
			var bUseBlocker = htOptions.bUseBlocker;
			var htParams = htOptions.htParams || null;
		}else{
			// for backward compatibility only
			var oAppRef = arguments[0];
			var elPlaceHolder = arguments[1];
			var sSkinURI = arguments[2];
			var fCreator = arguments[3];
			var fOnAppLoad = arguments[4];
			var bUseBlocker = arguments[5];
			var htParams = arguments[6];
		}

		if(bUseBlocker) nhn.husky.EZCreator.showBlocker();

		var attachEvent = function(elNode, sEvent, fHandler){ 
			if(elNode.addEventListener){
				elNode.addEventListener(sEvent, fHandler, false);
			}else{
				elNode.attachEvent("on"+sEvent, fHandler);
			}
		} 

		if(!elPlaceHolder){
			alert("Placeholder is required!");
			return;
		}

		if(typeof(elPlaceHolder) != "object")
			elPlaceHolder = document.getElementById(elPlaceHolder);

		var elIFrame, nEditorWidth, nEditorHeight;
		 

		try{
			elIFrame = document.createElement("<IFRAME frameborder=0 scrolling=no>");
		}catch(e){
			elIFrame = document.createElement("IFRAME");
			elIFrame.setAttribute("frameborder", "0");
			elIFrame.setAttribute("scrolling", "no");
		}
		
		elIFrame.style.width = "1px";
		elIFrame.style.height = "1px";
		elPlaceHolder.parentNode.insertBefore(elIFrame, elPlaceHolder.nextSibling);
		
		attachEvent(elIFrame, "load", function(){
			fCreator = elIFrame.contentWindow[fCreator] || elIFrame.contentWindow.createSEditor2;
			
//			top.document.title = ((new Date())-window.STime);
//			window.STime = new Date();
			
			try{
				nEditorWidth = elIFrame.contentWindow.document.body.scrollWidth || "500px";
				nEditorHeight = elIFrame.contentWindow.document.body.scrollHeight + 12;
				elIFrame.style.width =  "100%";
				elIFrame.style.height = nEditorHeight+ "px";
				elIFrame.contentWindow.document.body.style.margin = "0";
			}catch(e){
				nhn.husky.EZCreator.hideBlocker(true);
				elIFrame.style.border = "5px solid red";
				elIFrame.style.width = "500px";
				elIFrame.style.height = "500px";
				alert("Failed to access "+sSkinURI);
				return;
			}
			
			var oApp = fCreator(elPlaceHolder, htParams);	// oEditor
			

			oApp.elPlaceHolder = elPlaceHolder;

			oAppRef[oAppRef.length] = oApp;
			if(!oAppRef.getById) oAppRef.getById = {};
			
			if(elPlaceHolder.id) oAppRef.getById[elPlaceHolder.id] = oApp;

			oApp.run({fnOnAppReady:fOnAppLoad}); 
			
//			top.document.title += ", "+((new Date())-window.STime);
			nhn.husky.EZCreator.hideBlocker();
		});
//		window.STime = new Date();
		elIFrame.src = sSkinURI;
		this.elIFrame = elIFrame;
	};
	
	this.showBlocker = function(){
		if(this.nBlockerCount<1){
			var elBlocker = document.createElement("DIV");
			elBlocker.style.position = "absolute";
			elBlocker.style.top = 0;
			elBlocker.style.left = 0;
			elBlocker.style.backgroundColor = "#FFFFFF";
			elBlocker.style.width = "100%";

			document.body.appendChild(elBlocker);
			
			nhn.husky.EZCreator.elBlocker = elBlocker;
		}

		nhn.husky.EZCreator.elBlocker.style.height = Math.max(document.body.scrollHeight, document.body.clientHeight)+"px";
		
		this.nBlockerCount++;
	};
	
	this.hideBlocker = function(bForce){
		if(!bForce){
			if(--this.nBlockerCount > 0) return;
		}
		
		this.nBlockerCount = 0;
		
		if(nhn.husky.EZCreator.elBlocker) nhn.husky.EZCreator.elBlocker.style.display = "none";
	}
})();

**Comment by realmon** [comment]
왜 그런지 모르겠지만 갑자기 잘됍니다.
아무것도 수정한게 없는데 말이죠...

**Comment by kyungilpark** [comment]
오잉? @.@
해결되셨다니 다행이네요.

**Comment by matzip84** [comment]
https://blog.naver.com/matzip84/222601838223
