### ISSUE TITLE
smarteditor 사용중 문의 드립니다.

### ISSUE THREAD

**Issue by copulso** [naver/smarteditor2#108]
smarteditor를 적용해서 사용 중입니다.

그런데 
[table]
  [tr]
    [td]
      [textarea] smarteditor 적용1[/textarea]
    [/tr]
  [/td]
  [tr]
    [td]
      [textarea] smarteditor 적용2[/textarea]
    [/td]
  [/tr]
[/table]

위와 같이 [tr] 구분해서 사용하면 크기가 문제가 없으나 

[table]
  [tr]
    [td]
      [textarea] smarteditor 적용1[/textarea]
      [textarea] smarteditor 적용2[/textarea]
    [/td]
  [/tr]
[/table]
이렇게 구현을 하면 smarteditor 가 적용이 되기는 하나
첫번째 smarteditor는 크기가 원하는데로 보여지나
두번째 smarteditor는 크키가 작아집니다.

혹시 원인을 알 수가 있을까요?

두개의 smarteditor의 크기는 따로 잡아주지는 않았으며 기본적으로 되어 있는 크기를 사용하고 있습니다.

혹시 원인을 아시는 분이 계실까요?

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
