### ISSUE TITLE
사진 업로드시 이미지 경로

### ISSUE THREAD

**Issue by JungYongWook** [naver/smarteditor2#109]
안녕하세요 현재 에디터 2.8.2.3 버전 사용중입니다.

사진 업로드가 없어졌길래 구글링하여 사용 가능하도록 해놨는데요..

글 작성화면에서 사진을 업로드하면 textarea에 잘 붙는데,
작성 후 글을 보는 화면에서는 엑박으로 뜨네요
이미지 경로를 또 보니 경로의 양끝에 역슬래시가 붙어있어서 그러는데
왜 역슬래시가 붙는건지.. 어딜 수정해야할까요?

**Comment by JungYongWook** [comment]
그리고 이게 한번 확인할때마다 양쪽에 역슬래시가 하나씩 더생기는데 뭐가문제일까요ㅠㅠ

**Comment by kyungilpark** [comment]
서버저장 후의 데이터는 서버단 프로그램을 제가 알 수 없으니 도움드리긴 어려울듯합니다.
경로양끝에 역슬래시라고 하니 그냥 추측컨데 DB저장시나 혹은 화면단에 데이터를 내려줄때 문자열 처리하면서 따옴표에 대해 역슬래시를 잘못 붙여주고 있는게 아닐까 의심되네요..
