### ISSUE TITLE
아이폰 크롬에서 이미지 업로드시 항상 맨 위에 삽입 됩니다.

### ISSUE THREAD

**Issue by windstar2** [naver/smarteditor2#110]
안녕하세요.

아이폰 크롬에서 이미지 업로드시 편집기의 커서 위치에 삽입되는 것이 아니고,
항상 편집기의 맨 위에 삽입 됩니다.
아이폰에서 나타나는 현상 같은데요.

여기 답변에 https://github.com/naver/smarteditor2/issues/33
:: 팝업이나 다른 입력영역으로 포커스가 이동할때 range정보를 저장했다가 삽입이 호출되는 시점에 복원해주어야 합니다.
:: 특이케이스의 경우 직접 수동으로 저장/복원해주어야 합니다.
이렇게 수동으로 range 정보를 저장했다가 복원하는 것은 어떻게 해야 하는지요 ?

감사합니다.

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
