### ISSUE TITLE
갑자기 스마트에디터가 작동을 멈춘증상입니다.

### ISSUE THREAD

**Issue by hun741111** [naver/smarteditor2#111]
크롬에서 테스트 했습니다.

에디터의 모든 기능이 먹통이 되었습니다.

아래는 크롬의 콘솔에 나타난 오류입니다.

SmartEditor2Skin.html:17
GET http://www.bami.kr/wysiwyg/se2/js/smarteditor2.js net::ERR_CONNECTION_RESET 200 (OK)

SE2BasicCreator.js:21
Uncaught TypeError: nhn.husky.HuskyCore is not a constructor
    at createSEditor2 (SE2BasicCreator.js:21)
    at HTMLIFrameElement.<anonymous> (HuskyEZCreator.js:86)

**Comment by kyungilpark** [comment]
`nhn.husky.HuskyCore` 는 `smarteditor2.js` 파일에 정의되어 있습니다.
에러메시지로 보아 중간에 네트웍오류 등으로 `smarteditor2.js` 파일이 정상적으로 로딩되지 않은것 같습니다.
