### ISSUE TITLE
에디터 적용이 안되는 문제

### ISSUE THREAD

**Issue by dlrltjq1004** [naver/smarteditor2#113]
스마트에디터 사용자 가이드

2.0 버전 설치
http://naver.github.io/smarteditor2/user_guide/2_install/setting.html

참고하며 스마트 에디터를 적용 하였으나 적용이 되지 않음
파일 경로 문제인지 수 없이 확인 했지만 경로에는 이상이 없다고 판단 했습니다.

적용한 소스 및 파일 구조 이미지
![smartEditor](https://user-images.githubusercontent.com/48882958/59204776-4f3d6380-8bdc-11e9-9b3c-6961fe43cee9.PNG)

**Comment by dlrltjq1004** [comment]
> 스마트에디터 사용자 가이드
> 
> 2.0 버전 설치
> http://naver.github.io/smarteditor2/user_guide/2_install/setting.html
> 
> 참고하며 스마트 에디터를 적용 하였으나 적용이 되지 않음
> 파일 경로 문제인지 수 없이 확인 했지만 경로에는 이상이 없다고 판단 했습니다.
> 
> 적용한 소스 및 파일 구조 이미지
> ![smartEditor](https://user-images.githubusercontent.com/48882958/59204776-4f3d6380-8bdc-11e9-9b3c-6961fe43cee9.PNG)

**Comment by dlrltjq1004** [comment]
공식 예제에서 상단 스크립트 src 경로에  service가 빠져 있었네요 
당했습니다 ㅠㅠ
http://naver.github.io/smarteditor2/user_guide/2_install/setting.html

그냥 복붙한 제가 원망스럽습니다 흑흑

**Comment by kyungilpark** [comment]
엇 가이드문서 오류 제보 감사합니다. ㅠ.ㅠ

**Comment by kyungilpark** [comment]
수정배포하여 이슈 닫습니다.
