### ISSUE TITLE
사진 퀵 업로더 문의

### ISSUE THREAD

**Issue by dlrltjq1004** [naver/smarteditor2#114]
사진 퀵 업로드 샘플 파일이 2.90 버전부터 제거 되었는데
앞으로는 사진 퀵 업로드를 못 쓰는 건가요?

**Comment by kyungilpark** [comment]
사진첨부 샘플은 여기 답변(https://github.com/naver/smarteditor2/issues/21#issuecomment-296421874) 참고바랍니다.

툴바 사진첨부버튼은 여기 답변(https://github.com/naver/smarteditor2/issues/12#issuecomment-288339327) 참고바랍니다.
