### ISSUE TITLE
어느정도 글 입력 후 엔터 칠 경우

### ISSUE THREAD

**Issue by develper12** [naver/smarteditor2#116]
어느정도 글 입력 후에 엔터를 칠 경우에 
커서가 textarea 아래로 내려가서 보이질 않는 경우가 있네요 

스크롤바는 정상적으로 위로 올라가고요

화면이 커서따라 가게 하려면 어떤 곳을 수정하면 되나요?
![캡처](https://user-images.githubusercontent.com/51949119/59666629-2cb8d500-91f0-11e9-9753-81b964547799.PNG)

추가. 
확인해보니 스크롤이 생기는 순간부터 커서가 안보이게 되고 있습니다.

**Comment by kyungilpark** [comment]
textarea 라면 브라우저가 알아서 처리해줄텐데요...
어떤 경우를 말씀하시는지 잘 모르겠네요..
