### ISSUE TITLE
스마트에디터 지원 os 문의드립니다

### ISSUE THREAD

**Issue by air93** [naver/smarteditor2#117]
사용자 가이드 문서에는 
*지원운영체는 
 window xp, 7, vista / mac
*브라우저는
 ie7.x, 8.x, 9.x 
으로 나와있습니다.
window 10 에 ie11 에 적용하려는데 문제 없는지 문의 드립니다.

**Comment by kyungilpark** [comment]
네 아무 문제없습니다.
