### ISSUE TITLE
사진 업로드기능 관련 질문드립니다.

### ISSUE THREAD

**Issue by woejr2988** [naver/smarteditor2#118]
크롬에서 스마트에디터 사진첨부가   드래그형식인데,

크롬에서  [파일첨부] 버튼으로  변경하고싶습니다.

혹시 방법이나 참고할만한 정보가 있을까요?

**Comment by kyungilpark** [comment]
`attach_photo.js` 파일에서 다음과 같이 `checkDragAndDropAPI` 함수 호출부분 주석처리하시면 됩니다.
```js
	window.onload = function(){
  		// checkDragAndDropAPI();

```

**Comment by woejr2988** [comment]
> `attach_photo.js` 파일에서 다음과 같이 `checkDragAndDropAPI` 함수 호출부분 주석처리하시면 됩니다.
> 
> ```js
> 	window.onload = function(){
>   		// checkDragAndDropAPI();
> ```

감사합니다.
