### ISSUE TITLE
툴바에 사진 버튼이 없네요.

### ISSUE THREAD

**Issue by JinSeok-Ryu** [naver/smarteditor2#12]
안녕하세요.

여기 깃허브에서 다운 받아서 jsp 에 정상적으로 로드는 됬는데

툴바에 사진 버튼이 없네요.

SmartEditor2Skin.html

파일에 봐도 li 태그로 사진이 없네요.

js 파일도 뒤져봤더니 제가 못찾은 건지 안보여서 추가 하려면 어떻게 해야 하는지 여쭤봅니다.

사용자 가이드에는 버튼이 나와 있더군요.

**Comment by kyungilpark** [comment]
2.9.0버전부터 사진첨부서버샘플(php)이 소스저장소에서 제외되었습니다.
서버샘플이 없어서 동작하지 않아 마크업에서도 제거했습니다.

툴바사진버튼을 추가하고 싶으시면 534-535라인 사이에 다음과 같이 마크업 추가하시면 버튼이 노출될 겁니다.
```html
<ul class="se2_multy">
  <li class="se2_mn husky_seditor_ui_photo_attach"><button type="button" class="se2_photo ico_btn"><span class="se2_icon"></span><span class="se2_mntxt">사진</span></button></li>
</ul>
``` 
다음 릴리즈때 마크업은 다시 살려둬야겠네요..;;;
