### ISSUE TITLE
이미지 퀵 업로드 관련 질문 있습니다.

### ISSUE THREAD

**Issue by Jake-Shin** [naver/smarteditor2#122]
현재 프로젝트에 스마트에디트를 적용하여 사용중에 있습니다.
잘 쓰던 프로젝트를 똑같이 하나 더 만들어서 다른 버전으로 개발을 하고 있는 중인데요
스마트에디터 이용해서 사진 업로드를 하려고 하니까 사진을 드래그앤드롭을 한 뒤 확인(저장)버튼을 누르면 사진은 제대로 업로드 되지 않고 콘솔창에
![error](https://user-images.githubusercontent.com/44884955/62587020-06afd700-b8fb-11e9-82a1-9f72ffe769b0.png)

이런식으로 깨져서 나옵니다.
다른 프로젝트를 복사해서 만들었기 때문에 파일들이나 설정들은 다 똑같은 상태이고
인코딩도 UTF-8로 동일한 상태인데, 왜 이런 문제가 나오는지 알 수 없어 문의 드립니다.

**Comment by Jake-Shin** [comment]
아 감사합니다!
해결은 했었는데 해결 방법이 두번째 링크 주신거랑 비슷했습니다.
필터를 거쳐서 오도록 되어 있었는데 그 필터에서 뭔가를 하는 모양인거 같아요
답변 감사합니다!

**Comment by kyungilpark** [comment]
오옷! 해결되셨다니 다행이네요 ^^

**Comment by Jake-Shin** [comment]
kyungilpark 님 덕분에 해결할 수 있었습니다 감사합니다 !
