### ISSUE TITLE
추가기능문의

### ISSUE THREAD

**Issue by s2s22** [naver/smarteditor2#123]
에디터 text위에 부분에 input 넣을수잇을까요?
제목을 입력하는 부분을 만들고 싶어서 문의드립니다

**Comment by kyungilpark** [comment]
에디터 text 위라는건 어딜 말씀하시는건지?
툴바위쪽을 말씀하시는건지 툴바와 입력영역 사이를 말씀하시는건지요?
보통 제목은 툴바위쪽에 두긴하는데요..
만약 툴바와 입력영역사이에 두고 싶으신거라면 `SmartEditor2Skin.html` 에서 마크업수정하시면됩니다.
