### ISSUE TITLE
사진 퀵업로드

### ISSUE THREAD

**Issue by s2s22** [naver/smarteditor2#124]
사진 큅 업로드 대해서 문의드립니다

사용자 가이드에 보면 사진 퀵 업로더가 있는데 그 목록에 파일 구성에 photo_uploader라는 폴더가 있던데 최신버전 2.9.2에는 해당 폴더가 없습니다
2.8.3버전으로 다운받은뒤 사진 퀵 업로더방법을 적용하는 건가요?

진행하다가 사진 플러그인 추가 3번에서 /photo_uploader.html이 html파일이 없어서 문의드립니다
2.9.2 에다가 파일업로드 기능을 추가 하고 싶습니다
그냥 있는거 쓰려면 2.8.3을 쓰면되나요? 2.8.3버전을 다운로드하면 별다른 조치 없이 사진업로더 기능을 사용할수 있는건가요?
참고로 자바 스프링에서 작업하고 있는데 스프링 환경에서도 되는건가요?

그리고 마지막으로 내용이 저장될대  <p><p><br>이런 태그들이 있는상태로 출력되던데 없애는 방법을 알 수잇을가요?
감사합니다

**Comment by kyungilpark** [comment]
최신버전 그대로 사용하시고 샘플만 2.8.3 에서 받아서 연결하시면 됩니다.
- 사진첨부 샘플은 여기 답변(#21 (comment)) 참고바랍니다.
- 툴바 사진첨부버튼은 여기 답변(#12 (comment)) 참고바랍니다.
- 샘플은 php 기준으로 작성되어 있기 때문에 jsp 를 사용하신다면 서버코드는 직접 작성하셔야 합니다.

스마트에디터에서 작성된 글은 html 형식을 전달해드립니다.
html 태그정제는 별도로 처리하셔야 합니다.
