### ISSUE TITLE
IE에서 처음 작성 시 한글이 중복되어  작성됩니다.

### ISSUE THREAD

**Issue by Bilguun7** [naver/smarteditor2#125]
저 프로젝트에 Smart Editor 2.0를 쓰고 있는데 한글 입력 시 IE에서만 중복되어 작성됩니다:
예: 안녕하세요 -> ㅇ아안안ㄴ녀녕녕ㅎ하핫하세셍세요요

**Comment by kyungilpark** [comment]
IE8/IE9/IE10/IE11/Edge 모두 확인해봤는데 재현이 안됩니다.

재현되는 OS/브라우저 환경과 사용하시는 스마트에디터2 버전 확인부탁드립니다.

**Comment by Bilguun7** [comment]
IE 버전: 11.615.17763.0 이고요
스마트에디터2 버전: 2.8.2.12056 입니다

**Comment by kyungilpark** [comment]
음... 저희 테스트PC 환경에서는 재현이 안됩니다.
- OS: Windows 10 Enterprise(빌드 17763.615)
- IE: 11.615.17763.0
- 스마트에디터 : 2.8.2.12056

IE에 혹시 알툴바나 다른 애드온이 설치되어있어 영향을 받는게 아닌지 의심스럽니다.
애드온이 설치되어있는건 아닌지 다른 PC 에서 재현되는지 확인부탁드립니다.
