### ISSUE TITLE
이미지 가져오기

### ISSUE THREAD

**Issue by s2s22** [naver/smarteditor2#126]
지금까지 답변해주신거 감사합니다 덕분에 이미지까지 잘 구현했습니다

1. 이미지를 끌어온다음 확인을누르면 이미지는저장이되는데  ㅅ이미지를얼리는 창이안닫히고 textarea 에 업로드 되지않습니다
!!!!! 사진을 드래그하고 확인버틈을누르면 경로에 이미지는 잘저장이되지만 textarea 에는 등록이되지안습니다 ㅜㅜ
그것이 원인인지 textarea에 이미지를제외한입력한 문자만넘어갑니다ㅜㅜ
2. 현재 게시판을 만드는 것을 해보고잇는데 게시판을 수정할때 자신이 올린 이미지는 textarea 에 자겨오는 방법이 궁금합니다 exe함수를 이용하면되는지..아니면 제가그냥 생각해서 구현하면되는것인지 궁금합니다

감사합니다

**Comment by kyungilpark** [comment]
1. 서버에 파일이 잘 저장되어 있던가요? 파일이 정상적으로 업로드 되었는데도 이미지업로드창이 안닫히면 서버응답결과가 정상적으로 내려오지 않은 겁니다. `attach_photo.js` 파일에서 `makeArrayFromString` 함수부분이 정상적으로 호출되는지 디버깅해보세요.
2. 수정시 DB 에 저장되어 있던 html 데이터를 textarea 에 넣은 상태로 에디터를 실행시키면 자동으로 불러오게 됩니다. 이미지는 `<img src="이미지URL">` 형태의 html 로 저장되어 있을텐데 "이미지URL" 에 해당 이미지가 있으면 정상적으로 불러오게 됩니다.
