### ISSUE TITLE
사진첨부 버튼이 보이지 않습니다.

### ISSUE THREAD

**Issue by qnfqkr** [naver/smarteditor2#127]
툴바의 제일 우측에 있는 사진 버튼이 
특정한 환경에서 노출이 안되고 있습니다.
익스플로러와 크롬 모두에서 노출이 안되는데,
이러한 현상이 발생할 수 있는 원인에
어떠한 것들이 있는지 알고 싶습니다.

**Comment by kyungilpark** [comment]
html 에 해당버튼 마크업이 있는지 확인해보시고
마크업이 있는데도 노출이 안되는거라면 css 가 오버라이드된건 아닌지 확인해보세요

**Comment by qnfqkr** [comment]
모든 사용자들은 문제가 없는데
특정 한 군데에서만 사내 모든 PC와 노트북에서
에디터의 툴바에 있는 사진 버튼이 노출이 되지 않고 있는 현상입니다.
추측해볼 수 있을만한 게 어떤 것들이 있을까요?

**Comment by kyungilpark** [comment]
혹시 사진 버튼이미지가 스마트에디터2의 리소스와 다른 도메인에 있나요?
다른 곳은 이상없는데 특정 회사에서만 모두 노출이 안되는 상황이라면 특정도메인이 사내네트웍에서 차단되어 있는게 아닌가 싶습니다.
