### ISSUE TITLE
스프링시 이미지 업로드 문제

### ISSUE THREAD

**Issue by JinSeok-Ryu** [naver/smarteditor2#13]
안녕하세요. 어제 사진 버튼 없네요? 라고 했던 사람입니다. ㅋ

답변 주셔서 적용 시켰는데요.

문제가 발생해서 여쭤봅니다.

지금 현재 스프링을 사용 중인데(버전 3)

이미지 업로드 시에 스프링에서 인터셉터가 있으면 파일이 생성은 되는데 사이즈가 0 이 되더라구요.

인터셉터 없애고 하면 정상적으로 생성 잘 되구요.

현재 국가별 언어 설정 때문에 인터셉터를 뺄수 없는 상황인지라...

혹시 인터셉터 사용시에도 가능한 방법이 없는지 여쭤봅니다. ㅎ

**Comment by kyungilpark** [comment]
안녕하세요 @JinSeok-Ryu 님
ㅎㅎ 서버측에 어떤 인터셉터를 적용했는지 모르기 때문에 도움드리기는 어려운데요..

아시다시피 인터셉터나 필터들은 request, response에 대해 전/후 처리하기 위해 사용하는 녀석들입니다.
보통 파일업로드는 `multipart/form-data`형식으로 request가 넘어가기 때문에 중간에 변조가 일어나면 정상적인 파일을 얻을 수 없습니다.
적용하신 인터셉터가 언어 설정과 관련되어 있다고 하시니 `request parameter` 값들에 대해 `charset`인코딩/디코딩처리 등을 하지 않을까 싶은데 이 부분이 일괄처리 되다보니 그 과정에서 데이터가 손상되었을 가능성이 커보입니다.

해당 인터셉터 라이브러리의 버그가 아닐까 싶습니다만...
일반적으로 인터셉터/필터들은 설정파일을 통해 적용 URL을 지정할 수 있기 때문에 파일업로드 요청 URL만 인터셉터적용을 제외하도록 설정하는 것이 어떨까 싶습니다.
