### ISSUE TITLE
텍스트 붙여넣기 후, 엔터키를 입력해도 개행이 되지 않는 경우가 있습니다

### ISSUE THREAD

**Issue by zyubs** [naver/smarteditor2#14]
웹페이지에서 글을 복사해서 에디터에 붙여 넣거나(서식도 딸려옴)

워드문서(MS워드 및 한글)로 글을 작성한 후, 복사해서 에디터에 붙여 넣을 때,

Enter 키를 입력해도 개행(줄바꿈)이 되지 않는 경우가 있습니다.

사용하는 브라우저는 Chrome 입니다.(IE에서 발생하는 경우는 아직 못봤습니다)

**Comment by kyungilpark** [comment]
혹시 스크립트오류가 발생하나요?
현재 사용중인 SE2버전 정보 공유부탁드립니다.

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
