### ISSUE TITLE
사진퀵업로드 이미지 2번업로드

### ISSUE THREAD

**Issue by newssun90** [naver/smarteditor2#142]

**Comment by newssun90** [comment]
안녕하세요. HTML5에서 사진 업로드 시 이미지가 2번 업로드 되는현상입니다.
실제 리턴되는 fileInfo정보에는 하나의 이미지 정보만 있구요.
스크립트 디버깅중에 hp_SE2M_AttachQuickPhoto.js 의 $ON_SET_PHOTO 함수가 두번 호출됩니다.

처리할 수 있는방법이 있을까요~?

**Comment by newssun90** [comment]
해결완료 했습니다.
smarteditor2 버전은 최신인 2.10.0 을 사용했는데요.
/js/service/ 하위에 HuskyEZCreator.js , SE2BasicCreator.js,  SE2M_Configuration.js 소스를
https://github.com/naver/smarteditor2/releases/tag/v2.8.2.3
버전의 것으로 교체하니 정상적으로 하나씩 업로드됩니다.

**Comment by kyungilpark** [comment]
스마트에디터2에서는 pub/sub 방식을 사용합니다.
때문에 `$ON_SET_PHOTO` 함수가 두번 호출된다는 것은 플러그인이 중복으로 등록되었을 가능성이 있습니다.

혹시나 싶어 2.10.0 버전 설정파일들로 확인해봤지만 이상은 없었습니다.
일단은 2.8.2 버전 설정파일들을 교체하여 해결하셨다니 다행이네요.

해당 파일들은 설정/초기화 파일들이므로 서비스에 맞게 수정하여 사용하시면 됩니다.
