### ISSUE TITLE
이미지 첨부하고 글 등록 시 에러가 발생합니다.

### ISSUE THREAD

**Issue by chlgns128** [naver/smarteditor2#143]
![image](https://user-images.githubusercontent.com/35804960/63838359-29905100-c9b8-11e9-9a58-2e57e84711e6.png)
맨 처음 실서버에 서비스하였을 때 아무런 문제도 없다가 어느새 갑자기,
위 캡쳐본 처럼 이미지 업로드 시 _setBodyHeight가 무한 루프가 반복되다가 EMPTY_RESPONSE를 뿜어냅니다.
에러가 나더라도 이미지는 설정한 경로에 정상적으로 업로드 되구요.
이미지 없이 글귀만 등록할 경우에는 정상적으로 처리가 됩니다.
또 현재 실서버에서만 저런 버그가 발생하고 실서버와 동일한 환경인 개발서버에서는 
잘 돌아갑니다.(IP만 달라요)
정말 답답한 마음에 여쭈어 봅니다. 뭐가 원인일까요 ..

OS : CentOS release 6.9 (Final)
java : openjdk 1.8.0_201
tomcat 8.0

**Comment by kyungilpark** [comment]
`_setBodyHeight` 는 리사이즈 체크를 위해 주기적으로 반복 실행되는 메서드입니다.
업로드시 `EMPTY_RESPONSE` 를 뿜어내는 것과는 상관없습니다.

`EMPTY_RESPONSE` 는 서버 응답이 정상적이지 않아서 그런 겁니다.
서버로그확인이나 디버깅해보시는 확인하시는게 좋을것 같습니다.
OOM(OutOfMemoryException) 문제일수도 있습니다.
리얼서버는 항상 켜두기 때문에 메모리누수가 있으면 어느날 갑자기 원인을 알 수 없는 오류가 날 수도 있습니다.
http://digndig.net/?p=322
