### ISSUE TITLE
한글파일 이미지 복사 붙혀넣기 질문입니다

### ISSUE THREAD

**Issue by v0228ds** [naver/smarteditor2#144]
클립보드 이미지는

익스 크롬 잘 그려지는데요
한글파일에 있는 이미지만을 복사하여 붙혀넣으면
크롬은 이미지 붙으면서 "그림입니다~~~ 사이즈는 뭐뭐 " 이런식으로 텍스트 따라 들어오고요

익스는 텍스트만 붙습니다.

또 한글 문서에 글과 그림이 있을때 모두 선택하여 붙히면 익스,크롬 모두 이미지가 아닌 텍스트가 붙습니다

해결방법이 있을까요 ?

**Comment by v0228ds** [comment]
처음에 말한 클립보드 이미지는 캡처이미지 입니다.

**Comment by v0228ds** [comment]
한글 파일과 호환이 이루어져야 하는데 잘 안되는것 같아 질문 드립니다.

**Comment by kyungilpark** [comment]
붙여넣기시 별도 조작을 하지 않습니다.
한글프로그램과 브라우저간의 호환성 문제로 보입니다.
