### ISSUE TITLE
SmartEditor2Skin 에 사진 버튼은 있는데 적용 하면 사진 버튼이 안보여요

### ISSUE THREAD

**Issue by rkdqks456** [naver/smarteditor2#146]
<textarea name="content" id="ir1" rows="10" cols="100" style="width: 766px; height: 412px;">에디터에 기본으로 삽입할 글(수정 모드)이 없다면 이 value 값을 지정하지 않으시면 됩니다.</textarea>

var oEditors = [];
							nhn.husky.EZCreator.createInIFrame({
								oAppRef : oEditors,
								elPlaceHolder : "ir1",
								sSkinURI : "smarteditor/SmartEditor2Skin.html",
								htParams : {
									// 툴바 사용 여부
									bUseToolbar : true,
									// 입력창 크기 조절바 사용 여부
									bUseVerticalResizer : true,
									// 모드 탭(Editor | HTML | TEXT) 사용 여부
									bUseModeChanger : true,
									fOnBeforeUnload : function() {

									}
								},
								fOnAppLoad : function() {
									//기존 저장된 내용의 text 내용을 에디터상에 뿌려주고자 할때 사용
									oEditors.getById["ir1"].exec("PASTE_HTML",
											[ "기존 DB에 저장된 내용을 에디터에 적용할 문구" ]);
								},
								fCreator : "createSEditor2"
							});

현재 이렇게 사용중인데 상단에 툴바 다 나오는데 오른쪽 구석에 있어야 할 사진 버튼이 없어요.

skin 직접 켜보면 오른쪽 구석에 사진버튼은 존재 하는데 왜이러는거죠 ?

**Comment by kyungilpark** [comment]
혹시 오른쪽이 짤린건 아닌가요?
`iframe` 으로 들어가는거라 스킨만 열었을때 보인다면 `css` 문제는 아닐듯한데요..
