### ISSUE TITLE
스마트에디터에서 db데이터를 넣으면 마지막에 <br>태그가 붙어서 자동 개행이 됩니다.

### ISSUE THREAD

**Issue by kimyongwan** [naver/smarteditor2#147]
아래와 같이 스마트에디터 2.0 버전을 적어요하였는데요.

$(document).ready(function(){
	var oEditors = [];
	nhn.husky.EZCreator.createInIFrame({
	    oAppRef: oEditors,
	    elPlaceHolder: "nttCn",
	    sSkinURI: "/template/common/smarteditor/SmartEditor2Skin.html",
	    fOnAppLoad : function(){
	        oEditors.getById["nttCn"].exec("PASTE_HTML", ['${noticeVO.nttCn}']);
	    },
	    fOnBeforeUnload : function(){},
	    fCreator: "createSEditor2"
	});

	$(".formBtn").on("click", function(){
		oEditors.getById["nttCn"].exec("UPDATE_CONTENTS_FIELD", []);
        $("#frm").submit();
	});
});

데이터를 불러와서 에디터 입력창에 db값을 넣으면 마지막에

p ㅁㅁㅁㅁ/p
br

br값이 붙어서 나와서 수정없이 데이터를 update를 하면 자동개행이 됩니다.
해당 이슈를 어떻게 하면 br값이 안나오도록 할수 있을지 확인 부탁 드립니다.

**Comment by kyungilpark** [comment]
`oEditors.getById["nttCn"].exec("UPDATE_CONTENTS_FIELD", []);` 를 호출하면 `textarea` 에 값이 업데이트됩니다. `submit` 호출하기 전에 정제하시면 될 듯 합니다.
```js
$(".formBtn").on("click", function(){
    oEditors.getById["nttCn"].exec("UPDATE_CONTENTS_FIELD", []);
    $("#nttCn").value = $("#nttCn").value.replace(/<br>$/, "");
    $("#frm").submit();
});
```
