### ISSUE TITLE
HuskyCore 객체 생성 시 오류가 발생합니다.

### ISSUE THREAD

**Issue by Lee-Jung-Hoon** [naver/smarteditor2#148]
현재 적용 버전은 SE 2.10.0 버전입니다. 

IE8에서만 해당 에러가 발생하며 이후 버전에선 발생하지 않고 있습니다.

우선 smarteditor2.js에서 "SCRIPT445: 개체는 이 기능을 지원하지 않습니다." 오류가 발생합니다.
(smarteditor2.js는 직접 빌드하였습니다. webpack.config는 수정하지 않았습니다.)

`Object.defineProperty(exports, '__esModule', { value: true }); `

해당 코드에서 발생하는데 (웹팩쪽 에러로 보여집니다.)

이와 함께 SE2BasicCreator.js에서도 동일한 오류가 발생합니다.

`var oEditor = new nhn.husky.HuskyCore(htParams);`

해당 오류는 HuskyCore 객체 생성 시 나타납니다.

해당 오류가 발생하는 경우는 어떤 경우가 있을까요?

**Comment by kyungilpark** [comment]
넵 이미 아시다시피 webpack2 부터 ie8 을 공식지원하지 않습니다.
저도 이것 때문에 애먹었는데 최종적으로 바벨 폴리필로 설정을 맞춰놓긴 했습니다. https://github.com/naver/smarteditor2/commit/574067572a6bfadf82db79a3840ea4e26a0f3680

만약 최종빌드된 `smarteditor2.js` 를 찾지 못해서 직접 빌드하신거라면 빌드된 배포버전(https://github.com/naver/smarteditor2/releases/download/v2.10.0/smarteditor2-2.10.0.tgz) 을 사용하시기 바랍니다.

커스터마이징 때문에 직접 빌드가 필요하신거라면 설치된 npm 모듈들의 상세버전 문제일 수도 있으니 `package,json` 의 `devDependencies` 에 정의된 버전들과 일치하는지 확인하시고 버전을 맞춰서 시도부탁드립니다.
