### ISSUE TITLE
스마트데이터 문의

### ISSUE THREAD

**Issue by jewon7377** [naver/smarteditor2#149]
안녕하세요.
스마트에디터를 연동해서 이용중인데요.

특수문자를 이용할때 버릇처럼 한글+한자키클릭시 나오는 특수문자를 이용합니다.
에디터에서 위와같은 방법으로 이용시 특수문자를 생성시키고 옆에 글자를 치게되면 특수문자 사라집니다.

확인결과 익스, 파이어폭스에선 정상적이나 크롬에서는 안되는데요.
혹시 크롬의 버그로 봐야할까요?

지금 이글을 쓰고있는 에디터도 같은증상인데요.
원래 그런것인지, 아니면 처리할수있는 방법이 있는지 문의드립니다.

감사합니다.

**Comment by kyungilpark** [comment]
ㅂ

**Comment by kyungilpark** [comment]
넵 확인해봤는데 크롬 버그가 맞습니다.
https://support.google.com/chrome/thread/15023097?hl=ko
