### ISSUE TITLE
에디터 상단의 버전 표시 삭제 방법

### ISSUE THREAD

**Issue by ktw-github** [naver/smarteditor2#15]
안녕하세요. 
에디터를 붙이면 에디터 바로 위에 아래같은 버전이 자동으로 붙어서 표시됩니다.

**Version: 2.9.0.4a256db**

제가 뭔가 잘못했을까 해서 안에 포함되어 있는 샘플페이지를 확인해도 똑같이 버전이 표시됩니다.

왜 버전을 자동으로 표시되도록 해놓으셨는지 잘 모르겠고,
삭제할 수 있는 방법이 있나요?

**Comment by kyungilpark** [comment]
안녕하세요
데모버전 확인을 위해 삽입되어있습니다.
`SmartEditor2Skin.html`파일에서 아래 부분 삭제하시면 됩니다.
```html
<span id="rev">Version: 2.9.0.4a256db </span>
```

**Comment by ktw-github** [comment]
스킨에 아예 포함되어 있는거였군요.

감사합니다.
