### ISSUE TITLE
최신버전 smarteditor2.js 질문드립니다.

### ISSUE THREAD

**Issue by nyorong** [naver/smarteditor2#150]
안녕하세요. 

2.10 받을때 smarteditor2.js 을 따로 받는방법이있나요? 

개발 초짜라 어디서 구해야할지 잘 모르겠어서 그냥 구버전 2.92 사용하게됬는데, 궁금해서 질문글 남겨봅니다.

**Comment by Ta2Rim** [comment]
안녕하세요
https://github.com/naver/smarteditor2/releases 여기도 있고
그냥 맨처음들어오셨을 때 클론받으시면 제일 최신버전인 2.10이 나옵니다.

**Comment by kyungilpark** [comment]
빌드된 `smarteditor2.js` 만 취하고 싶으신거라면
https://github.com/naver/smarteditor2/releases/tag/v2.10.0 에서 [smarteditor2-2.10.0.tgz](https://github.com/naver/smarteditor2/releases/download/v2.10.0/smarteditor2-2.10.0.tgz) 다운받아 압축푸시면 됩니다.
압축푸시면 `package/dist/js` 폴더에 있습니다.

**Comment by nyorong** [comment]
아 제가 받은 10.0 버젼 zip파일에선 smarteditor2.js 파일만없어서 그랬습니다. tgz파일에 있었군요, 답변해주신분들 감사합니다.

**Comment by jihyunleeme** [comment]
이슈 올려주셔서 감사합니다. 저도 2.10.0.zip파일로 받았는데 smarteditor2.js가 없어 404 not found error가 뜨더라구요. 덕분에 해결했습니다.

**Comment by jeongdaeahn** [comment]
정보공유 감사합니다. 저도 zip파일 받아서 해멨네요
