### ISSUE TITLE
사진 업로드 보안취약점 관련 문의

### ISSUE THREAD

**Issue by rhee2871** [naver/smarteditor2#153]
안녕하세요. 아래와 같은 내용을 문의를 드립니다.
스마트에디터 보안취약점 권고 사항으로 스마트에디터 최신버전으로 업데이트를 완료하였습니다. 
최신버전에 보면 사진 업로드 기능이 빠진 상태로 되어 있는데 이 기능을 반드시 사용해야 한다면 보안취약점에 위배되는 건지, 
보안취약점 패치가 적용되었는데 그냥 기능을 빼놓은 건지,
보안취약점 관련 이슈가 있는 곳이라면 이 기능을 빼는 것이 맞는 것인지
정확한 정보를 알고 싶습니다.

**Comment by kyungilpark** [comment]
음... 좀 조심스러운 부분이 있는 주제라 답변드리기 애매한데요...

---
1. 일단 사진업로드 샘플은 서버연동기능을 구현의 이해를 돕기 위한 단순 예제일 뿐입니다.
스마트에디터2 는 순수 JS 라이브러리로 PHP 업로드 예제는 스마트에디터2 의 일부가 아님에도 PHP 업로드 예제에서 발생하는 보안취약점이 마치 스마트에디터2 자체의 보안취약점인 것처럼 오해하는 경향이 있어서 소스에서 제외하였습니다.
2. 마지막에 포함된 사진업로드 예제는 그 당시까지 보고된 보안취약점은 당연히 방어처리되어 있습니다.
하지만 불멸의 방패란 없습니다. 보안은 창과 방패처럼 언제든 뚫고 막고 를 반복합니다.
게다가 스마트에디터2 라이브러리와 PHP 업로드 예제의 방어처리가 완벽하다고 하더라도 이와는 별개로 사용하시는 웹서버나 PHP서버, DB서버 자체 취약점이 있을 수도 있습니다.
따라서, 보안취약점에 위배된다 안된다의 문제가 아니라 보안취약점이 발견되면 빠른 시일내에 조치하는 것이 중요합니다.
