### ISSUE TITLE
스마트 에디터에서 다른 HTML을 불러올수 있을까요?

### ISSUE THREAD

**Issue by yunix-dev** [naver/smarteditor2#154]
회사에서 사용하는 양식이 있는데 그 양식을 그대로 html 로 그린 후 스마트 에디터에서 가져다가 사용하고 싶은데 가능할까요?

**Comment by kyungilpark** [comment]
어느정도 수준까지를 원하시는 건지 모르겠지만
새글을 작성할때 자주 사용하는 템플릿을 미리 넣으시려는 것이라면 `fOnAppLoad` 옵션에서 삽입하시면 될 것 같습니다.
https://github.com/naver/smarteditor2/blob/9c506cb80b47e8ab4d708da7f628c865b885c559/workspace/static/SmartEditor2.html#L43-L46

**Comment by yunix-dev** [comment]
감사합니다 한번 시도해보겠습니다
