### ISSUE TITLE
createInIFrame함수로 에디터 만들때 textarea를 읽기전용 readonly로 할수는 없나요?

### ISSUE THREAD

**Issue by ddinggill** [naver/smarteditor2#155]
연결하는 textarea에 reanonly 속성을 줘도 먹히지가 않던데
좀 찾아보니 iframe 방식인거같은데 SmartEditor2Skin.html파일의 iframe에 클릭이벤트를 막으면
클릭해도 커서가 안생겨서 되긴하는데 문제는 내용이 길떄 스크롤바도 클릭이 안먹혀서 내용을 전부
볼수가 없네요.. createInIFrame로 만들때 뭐 속성값을 주거나 할수는 없나요?
그리고..
ajax로 데이터를 요청하고 결과를
oEditors.getById["filelogTb"].exec("SET_IR", [""]); //textarea 내용 초기화
oEditors.getById["filelogTb"].exec("PASTE_HTML", [result]); //결과 textarea에 삽입
oEditors.getById["filelogTb"].exec("UPDATE_CONTENTS_FIELD",[]); //textarea 업데이트

이렇게 입력해주는데 textarea에 들어가는 데이터의 양이 많아지니까 멈춰버리던데
이건 저희가 처리할수 있는 부분이 아닌가요? 몇일째 구글링해도 답이 없어서 부탁드려요 ㅠ

**Comment by kyungilpark** [comment]
스마트에디터2 를 띄우는 시점에 readonly 처럼 하시려면 다음과 같이 `fOnAppLoad` 함수에서 다음과 같이 호출해주시면 될것 같습니다.
```js
nhn.husky.EZCreator.createInIFrame({
	...
	fOnAppLoad : function(){
		//예제 코드
		//oEditors.getById["ir1"].exec("PASTE_HTML", ["로딩이 완료된 후에 본문에 삽입되는 text입니다."]);
		var editor = oEditors.getById["filelogTb"];
		editor.exec("DISABLE_WYSIWYG");
		editor.exec("DISABLE_ALL_UI");
	},
```

데이터량이 많을때 멈추는 케이스는 재현이 가능한 `샘플데이터` 와 `브라우저 환경` 공유해주시면 확인해보겠습니다.

**Comment by ddinggill** [comment]
덕분에 문제가 잘 해결됐습니다.
친절한 답변 감사합니다
