### ISSUE TITLE
스마트에디터 이미지 복사 붙여넣기 사용안되게 가능할까요?

### ISSUE THREAD

**Issue by KimSeungSu81** [naver/smarteditor2#156]
익스플로만 이미지 복사 붙여넣기 가능한데 코드로 변환되서 느리기도하고 문제가 있어서 안되게 하고 싶은데 방법 있으면 전수 부탁드립니다.

**Comment by kyungilpark** [comment]
제 기억으로는 IE 는 paste 이벤트에서 text 이외에는 클립보드 정보를 알 수 없습니다.
때문에 붙여넣기가 된 후에 base64 로 들어간 이미지태그를 찾아서 제거하는 수 밖에 없을듯 합니다.
