### ISSUE TITLE
버전 확인 방법은 따로 없나요?

### ISSUE THREAD

**Issue by hunchulchoi** [naver/smarteditor2#157]
이번에 스마트에디터 2.10.0으로 업데이트 했는데

고객에게 확인 시켜줘야 되는데 에디터 창에서 확인 하는 방법은 없나요?

**Comment by kyungilpark** [comment]
`oEditors.getById["ir1"].version.number` 로 확인하시면 됩니다.

**Comment by hunchulchoi** [comment]
> `oEditors.getById["ir1"].version.number` 로 확인하시면 됩니다.

감사합니다.

**Comment by symtra** [comment]
oEditors.getById["ir1"].version.number

**Comment by kimhoyong** [comment]
저도 이번에 스마트에디터 2.10.0으로 업데이트 했는데

console(oEditors.getById["ir1"].version.number); 로 찍어보면

Cannot read properties of undefined (reading 'number') 라고 에러가 발생하고 있어서요

성공하신 분들 ... oEditors.getById["ir1"].version.number  활용 방법 부탁드립니다.

**Comment by kimhoyong** [comment]
자문자답
2.9.0 버전에서는 확인이 가능하지만
2.10.0 버전에서는 에러발생
