### ISSUE TITLE
firefox 버그 문의

### ISSUE THREAD

**Issue by netfron** [naver/smarteditor2#159]
스마트에디터2가 firefox에서는 아래 오류가 발생하면서 되었다가 안되었다가 하네요. 
[데모사이트](http://naver.github.io/smarteditor2/demo/)에서도 발생합니다. 에디터 로딩이 실패하면 게시물을 저장시 글내용이 날아가는 이슈가 있어서 공유드립니다.

firefox version : 71.0

`
InvalidAccessError: A parameter or an operation is not supported by the underlying object smarteditor2.js:1
    addCSSClass http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    $LOCAL_BEFORE_FIRST http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _execHandlerWithoutDebugger http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _execMsgHandler http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _execMsgStepWithoutDebugger http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _doExec http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _execWithoutDebugger http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _exec http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    $ON_MSG_APP_READY http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _execHandlerWithoutDebugger http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _execMsgHandler http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _execMsgStepWithoutDebugger http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _doExec http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _execWithoutDebugger http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _exec http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _changeAppStatus http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    _waitForPluginReady http://naver.github.io/smarteditor2/demo/js/smarteditor2.js:1
    o http://naver.github.io/smarteditor2/demo/js/lib/jindo2.all.js:3
`

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
