### ISSUE TITLE
editor창 내부에는 외부에 적용된 css가 적용되어 보이지가 않아요. 해결방법 있을까요?

### ISSUE THREAD

**Issue by wookee2** [naver/smarteditor2#16]
migration(v2.9.0) 버전 받아서 적용중에 어려움이 있어서 질문 올립니다.
editor 창 내부 글은 editor 바깥 부분에 적용된 css들이 적용되어 표시되지 않습니다.
editor 창 내부에서 외부 css를 reset시키는 부분이 있나요?
도와주세요.

**Comment by kyungilpark** [comment]
editor창 내부에서 외부 css를 reset시키지는 않습니다.
editor 편집영역이 외부 css의 영향을 받게 되면 적용하는 서비스환경마다 다른 css로 인해 충돌나는 문제들을 일일이 해결할 수가 없기 때문에 iframe으로 격리되어 있습니다.
편집영역에 적용되는 css파일은 `smart_editor2_in.css`입니다.
해당 파일에 서비스용 css를 추가해서 이상이 없는지 확인부탁드립니다.

**Comment by kyungilpark** [comment]
이슈정리차원에서 닫습니다.
