### ISSUE TITLE
에디터에 이미지 삽입 후에 이미지 사이즈를 변경하고 싶은데

### ISSUE THREAD

**Issue by lcoguss** [naver/smarteditor2#160]
현재 설치된 에디터 버전은 가장최신의 2.10? 인가 받아서 적용했어요.

보완취약점 이슈 때문인지 사진첨부기능이 빠졌길래, 

샘플에 있는거 토대로 해당 js lib 에서 호출되는 함수 안쓰고 그냥 에디터에 우겨 넣었더니

일단은 이미지가 잘 들어가긴 하는데 

첨부된 후에 이미지 영역을 마우스로 잡을수가 없네요

혹시 에디터 설정에 이와 관련한 옵션이 있는것인지 아니면

이미지 첨부 후 크기 변경이나 작성중인 글 내에서 위치 변경을 하는 그런 예제가 

있을런지요?

**Comment by lcoguss** [comment]
음...계속 이것저것 테스트 해보니

IE 에서는 별다른 설정 없이 이미지 영역이 잡혀서 크기변경이 되네요.

크롬위주로 사용하다보니...

크롬에서 해결방법 있을까요?

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
