### ISSUE TITLE
editor 모드로 전환시 getEditingMode 속성이나 메서드를 지원하지 않습니다. ???

### ISSUE THREAD

**Issue by google007049** [naver/smarteditor2#161]
View 모드로 조회후 편집모드로 전환하면 View 모드로 조회된 내용을 
편집모드에 setContents()하는 로직입니다. 
그런데 Editor가 보여지기전에 
****" 개체가 getEditingMode 속성이나 메서드를 지원하지 않습니다"**** 라는 스크립트 오류가 
나타납니다. 
그러나 setContents()하기전에 메세지박스를 한번 뿌리고 그다음 setcontents()를 하면 잘 되구요. 

아래와 같은 스크립트입니다. 
messagebox('확인','프로그램 도움말을 입력/수정합니다.')
u_editor.resetcontents()		
u_editor.setcontents(is_contents) //is_contents는 viewer모드에서 조회된  내용입니다.

무슨 문제가 있을까요?

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
