### ISSUE TITLE
이미지 업로드 예제

### ISSUE THREAD

**Issue by js-baek** [naver/smarteditor2#162]
스마트에디터에 이미지 업로드 기능을 추가하고 싶은데요. 가이드에 있는 /quick_photo_uploader 폴더가 소스파일에는 없습니다. 어디서 받아야하나요?

**Comment by zzins** [comment]
https://github.com/naver/smarteditor2/releases/tag/v2.8.2.3
여기에서 파일 다운로드 후에 압축을 풀어 보시면 sample이라는 폴더가 있습니다.

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
