### ISSUE TITLE
에디터 텍스트 정렬 기본값을 수정하고싶습니다.

### ISSUE THREAD

**Issue by AnYunJin** [naver/smarteditor2#164]
에디터 적용 시 정렬의 기본값인 왼쪽 정렬을 양쪽 정렬로 수정하는 방법을 알고싶습니다!
에디터 로드 시 default 설정은 양쪽 정렬로 변경하였지만, 에디터 영역 수정 시(이벤트 발생)  왼쪽 정렬로 돌아가는 이슈가 발생하여 버전에 상관없이 스크립트 수정이 가능한지 문의드립니다.

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
