### ISSUE TITLE
스마트에디터 사용 중 fCreator is not a function 오류가 발생했습니다. 

### ISSUE THREAD

**Issue by canolatte** [naver/smarteditor2#165]
도통 원인을 찾지 못하고 있습니다.
혹시 해결책을 아시는 분께서는 도와주시면 감사하겠습니다ㅜ
인터넷 익스플로러, 크롬 둘 다 동일한 에러가 발생하네요.

> ![image](https://user-images.githubusercontent.com/53788007/71243810-77103f80-2354-11ea-8149-9663d6c0992b.png)

스킨은 불러왔는데 elPlaceHolder와 동일한 명칭을 ID로 준 textArea에 스킨이 적용된 게 아니라
그 아래에 따로 생겼습니다. 도움 부탁드립니다.

![image](https://user-images.githubusercontent.com/53788007/71244663-6234ab80-2356-11ea-8b32-167c909c0aa8.png)

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
