### ISSUE TITLE
IE 에서 한글 깨짐 현상

### ISSUE THREAD

**Issue by HyosubShin** [naver/smarteditor2#167]
• 버전 : IE: 11.914.17763.0
• 테스트 환경 : http://naver.github.io/smarteditor2/demo/
   - Editor tab 에서 입력

• 한글 입력시 증상 : ㄱ가강가입입 가입대상 
• IE에서 **width: calc(100% - 320px);  float: right;** 해당 스타일 사용시 한글 입력 깨짐 현상이 발생 하는것 같습니다. 테스트 한 Tag 일부 첨부하겠습니다.

**div style="width: calc(100% - 320px); float: right;"** 
스타일 추가해서 테스트 부탁드립니다.

**Comment by kyungilpark** [comment]
IE 버그입니다.
https://answers.microsoft.com/ko-kr/ie/forum/all/%ED%95%9C%EA%B8%80/4f40274d-badf-4ab2-9119-c22a179f7483
브라우저 자체 버그인데 스마트에디터에서 회피할 방법이 없습니다.
