### ISSUE TITLE
한글문서에서 복사 후 붙여넣기 시 줄 간격 깨짐 (크롬)

### ISSUE THREAD

**Issue by Jeffrey-Oh** [naver/smarteditor2#170]
한글 문서에서는 line-height가 정상적으로 130%나 160% 이렇게 설정되어있고

복사해서 스마트 에디터에 붙여넣기하면

line-height 속성들이 크롬브라우저에서만 <p> 태그들에 대해 style 속성으로 px 단위로 들어갑니다.

IE, 웨일 에서는 % 단위로 들어가는게 확인이 되었고

크롬에서만 px단위로 들어가는데 잘 사용하다가 크롬 80 업데이트 후 문제가 발생한것으로 추측합니다.

**Comment by Jeffrey-Oh** [comment]
![1](https://user-images.githubusercontent.com/45170847/73994332-85fc9100-4998-11ea-9c12-89c37b407cd7.png)

위 이미지는 크롬 80 에서의 p태그 style 값입니다.

![2](https://user-images.githubusercontent.com/45170847/73994333-872dbe00-4998-11ea-8259-2bd46239a76a.png)

위 이미지는 네이버웨일에서의 p태그 style 값입니다.

같은 내용 복사붙여 넣기해도 style 적용이 다르게되고있습니다.

**Comment by kyungilpark** [comment]
클립보드 접근 제약사항이 있기 때문에 복/붙시 스마트에디터에서 별도 보정을 하지 않습니다.
크롬 업데이트이후로 발생한것으로 보아 브라우저 자체 버그로 보입니다.
