### ISSUE TITLE
이미지 복사 붙여넣기 방식 시 오류

### ISSUE THREAD

**Issue by 1224chopper** [naver/smarteditor2#171]
스마트 에디터에 복사 붙여넣기 방식으로 진행 시 이미지 코드가 307만 글자로 변경됩니다.
혹시 이유랑 해결방법을 알 수 있을까요?
![image](https://user-images.githubusercontent.com/61268964/74913421-f0371c00-5403-11ea-9d9f-ad1fb46a1c56.png)

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
