### ISSUE TITLE
quick_photo_uploader는 어디서 다운받을 수 있는 건가요?

### ISSUE THREAD

**Issue by TrueGuy** [naver/smarteditor2#174]
http://naver.github.io/smarteditor2/user_guide/2_install/download.html

가이드북에는 분명 quick_photo_uploader 폴더가 나와있는데 여기에는 없네요...

**Comment by kyungilpark** [comment]
사진업로드예제는 관리이슈때문에 github 으로 이전하던 시점(v2.9.0)부터 소스코드에서 제외되었습니다.

- 사진첨부 샘플은 여기 답변(https://github.com/naver/smarteditor2/issues/21#issuecomment-296421874) 참고바랍니다.
- 툴바 사진첨부버튼은 여기 답변(https://github.com/naver/smarteditor2/issues/12#issuecomment-288339327) 참고바랍니다.
