### ISSUE TITLE
안녕하세요 iframe 질문 입니다. 

### ISSUE THREAD

**Issue by lyg0114** [naver/smarteditor2#175]
에디터에서 <iframe>태그를 사용하여 유투브 동영상을 불러오려고 하는데요
bSkipXssFilter 값을 true로 설정하고 나서 게시물을 업로드 하니 

frame  태그에 

<x-ix-frame src="https://www.youtube.com/x-embed/(유투브키)  x-frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></x-ix-frame>

이런식으로 <iframe 태그 앞에 x-ix 라는 문자가(<x-ix-frame) 
embed 앞에도 x라는 문자가(x-embed)
frameborder 에도 x 라는 문자가 추가 되어 동영상을 불러올 수 없는데요.(x-frameborder)
 
혹시 이 문제를 해결할 수 있는 방법 있을까요??

**Comment by kyungilpark** [comment]
`x-ix`, `x-` prefix 는 스마트에디터에서 붙여주는 값이 아닙니다.
서버에 저장하실때 서버측에서 보안필터링하는 것으로 보입니다.
서버측 보안필터라이브러리를 확인하시기 바랍니다.
