### ISSUE TITLE
IE에서 style position값이 absolute 인경우, 한글입력시 자소 분리현상

### ISSUE THREAD

**Issue by feedback13** [naver/smarteditor2#178]
• 브라우저 버전 : IE: 11.0.9600.19596 (업데이트 버전: 11.0.170)

**• 한글 입력시 증상 : ㅎㅏㄴㄱㅡㄹ**
• 특정 템플릿을 에디터에 세팅한후, style 의 position값이 absolute인 div영역에서 한글 입력시 위와 같이 한글과 모음이 분리되서 입력이 됩니다. 
 position 값을 absolute 값이 아닌경우에는 정상적으로 입력이 됩니다.

`<div style="height: 100px; position: relative;"><div style="left: 0px; top: 0px; position: absolute;">ㅎㅏㄴㄱㅡㄹ</div></div>`

**Comment by kyungilpark** [comment]
IE 버그입니다.
https://answers.microsoft.com/ko-kr/ie/forum/all/%ED%95%9C%EA%B8%80/4f40274d-badf-4ab2-9119-c22a179f7483
브라우저 자체 버그인데 스마트에디터에서 회피할 방법이 없습니다.
