### ISSUE TITLE
IE11, window7 편집모드에서 테스트 입력시 자소분리 되는 현상

### ISSUE THREAD

**Issue by ipadorusa** [naver/smarteditor2#179]
텍스트 입력 하는 부모의 포지션이 absolute일때 테스트를 수정하면 자소 분리가 되어서 나옵니다.

예) 테스트 => ㅌ ㅔ ㅅ ㅡ ㅌ ㅡ

**Comment by kyungilpark** [comment]
IE 버그입니다.
https://answers.microsoft.com/ko-kr/ie/forum/all/%ED%95%9C%EA%B8%80/4f40274d-badf-4ab2-9119-c22a179f7483
브라우저 자체 버그인데 스마트에디터에서 회피할 방법이 없습니다.
