### ISSUE TITLE
스마트에디터 사용 명시 관련

### ISSUE THREAD

**Issue by JeongDaIn** [naver/smarteditor2#18]
안녕하세요.
스마트 에디터를 사용해서 웹페이지를 만드려고 하는데 공지사항에 보면 

2 외부에 SmartEdior Basic가 포함된 S/W를 배포혹은 판매 하고자 하는 경우 주의 사항
a. SmartEditor Basic 가 사용됐음을 반드시 고지 해야 합니다
b. SmartEditor Basic 가 LGPL V2 라는 사실도 함께 고지 해야 합니다

이런글이 있더라고요.

외부에 SmartEdior Basic가 포함된 S/W 의 범위와

a. SmartEditor Basic 가 사용됐음을 반드시 고지 해야 합니다
b. SmartEditor Basic 가 LGPL V2 라는 사실도 함께 고지 해야 합니다

이 고지를 어떤식으로 하는지 예시가 있으면 알려주시면 감사하겠습니다.

**Comment by kyungilpark** [comment]
안녕하세요.

보통 오픈소스 제품들은 README나 홈페이지 등에 해당 제품에서 사용한 오픈소스 라이브러리와 라이선스를 명시합니다.

오픈소스처럼 공개페이지가 없는 상용 제품의 경우는 배포 패키징 파일안에 사용한 라이브러리와 라이선스를 명시한 파일을 포함해서 배포합니다. (apache httpd 나 tomcat 설치하면 설치폴더 루트에 있는 LICENSE 파일 열어보시면 자기들 라이선스와 함께 sub모듈로 사용한 라이브러리들의 라이선스들이 명시되어 있는 것을 확인하실 수 있습니다. httpd 나 tomcat처럼 한 파일에 쭈욱 명시해도 되고 LICENSE라는 폴더를 하나 만들어서 모듈별 라이선스파일을 분리해서 넣어도 상관없습니다.)

그리고 se2의 js파일을 열어보시면 최상단에 라이선스 주석이 붙어있는데 임의로 지우지만 않으시면 됩니다.
