### ISSUE TITLE
스마트에디터 모바일버전도 무료 연동가능한가요?

### ISSUE THREAD

**Issue by pinkpooh** [naver/smarteditor2#180]
홈페이지 관리자페이지를 개발하려는데 스마트에디터를 연동하려고 합니다.
모바일 버전도 무료로 연동할 수 있는지 아님 추가비용이 발생하는지 궁금합니다.
또는 단계적으로만 무료로 연동가능한 것인지도 답변 부탁드립니다.

**Comment by kyungilpark** [comment]
제가 질문의 잘 이해못했는데 모바일버전이라 함은 무엇을 말씀하시는건지요?
기본적으로 모바일대응은 되어있지만 모바일용UI 스킨은 제공하고 있지 않아서 스킨을 만드셔야 합니다.
