### ISSUE TITLE
크롬 브라우저 진도 프레임워크 인식오류

### ISSUE THREAD

**Issue by ChoByeongSeong** [naver/smarteditor2#181]
잘되던 네이버스마트 에디터가 갑자기 크롬에서 사용하려니
진도 프레임워크 2를 지원하지 않는다고 1.5.3을 다운받아 사용하라는데 
jindo.min.js를 추가하고 스크립트에 추가했는데도 
해당 오류가 사라지지 않네요 
같은 파일을 서버에 업로드하면 서버에서 동작할때는 해당 오류가 안나오고
로컬에서 작업할 때 오류가 나옵니다.
이유가 뭘까요..
또 크롬에선 안되는데
엣지에서는 위 오류가 뜨지는 않고 사진첨부할때 드래그하는 부분이 안되고 복잡합니다. ㅠ
원인을 모르겠습니다.

**Comment by kyungilpark** [comment]
1.5.3 을 다운받으라는 문구가 어디서 나오는 걸까요?
smarteditor2 번들에 포함된 진도버전은 `1.5.2-SMART_EDITOR` 버전입니다.
아무래도 다른 버전의 진도가 함께 로딩되어서 컨플릭이 발생하는게 아닌가 싶습니다.
브라우저마다 로딩되는 속도나 순서가 달라서 그럴 수 있습니다.
개발자 콘솔에서 `jindo.$Jindo().version` 입력하면 진도버전 확인할 수 있습니다.
