### ISSUE TITLE
스마트에디터2 블로그 포맷설정

### ISSUE THREAD

**Issue by blueday321** [naver/smarteditor2#184]
웹페이지 연동시 스마트에디터2
![20200622_130724](https://user-images.githubusercontent.com/67254125/85250186-d16b9380-b490-11ea-9d78-3e3faabeefe4.png)

블로그 작성 시 스마트에디터2
![20200622_115241](https://user-images.githubusercontent.com/67254125/85250190-d29cc080-b490-11ea-97d2-27382be001c7.png)

블로그 에디터와 같은 포맷(플러그인)으로 에디터를 연동요청으로 스마트에디터2를 다운받았습니다. 
샘플페이지에는 베이직 툴바만 셋팅되어있어 블로그 툴바와 같은 플러그인(수식, 투표, 일정, 글장식, 글양식, 스티터)을 연동해야 할 경우 어떻게 진행해야 하는지 가이드 요청 드립니다. 
감사합니다.

**Comment by kyungilpark** [comment]
블로그에 적용된 스마트에디터는 네이버내부기능을 포함하고 있기 때문에 공개가 불가합니다.
직접 마크업과 플러그인을 구현하셔야 합니다.
http://naver.github.io/smarteditor2/user_guide/3_customizing/
