### ISSUE TITLE
Smart Editor2 정렬시 map-area 태그 사라짐 문제

### ISSUE THREAD

**Issue by nett-edgge** [naver/smarteditor2#186]
안녕하세요, Smart Editor2를 이용중에 버그가 의심되는 부분이 있어 문의 드립니다.

img 태그 하나와 그 밑에 바로 map-area 태그를 넣은 소스를 에디터에 넣고

에디터의 정렬 버튼을 누르면 IE는 정상 작동하지만 크롬, 웨일 등의 브라우저에서는

정렬은 적용되고 아래쪽의 map-area 태그가 사라지는 현상이 있습니다.

이런 경우 에디터의 어느 부분을 손봐야할까요? 찾다 찾다 잘 안찾아져서 문의드립니다.

<!img src="test.jsp" usemap="#T1">
<!map name="T1">
<!area ~~~>
<!/map>

이 소스를 크롬에서 스마트 에디터에 넣고 정렬 버튼을 누르면

<!div style="text-align: center;" align="center"><!img src="test.jsp" usemap="#T1"><!/div>

이렇게 변합니다.(태그 앞에 느낌표는 무시해주세요.)

이거 어느 부분을 손봐야할까요

**Comment by nett-edgge** [comment]
아 이거 수정이 안되네요..;;

저 엑박 이미지 들어가 있는 부분은 아래와 같습니다

- 정렬전 -
<!img src="test.jsp" usemap="#T1">
<!map name="T1">
<!area ~~~>
<!/map>

- 정렬 버튼 누른 후 -
<!div style="text-align: center;" align="center"><!img src="test.jsp" usemap="#T1"><!/div>

(태그를 표시하기 위해 태그 앞에 !를 붙였습니다 무시해주세요)

보시다시피 map과 area 태그가 사라집니다..(크롬, 웨일에서 확인)
왜 이럴까요ㅠ

**Comment by kyungilpark** [comment]
정렬은 문단 단위로 이루어지는데 문단의 구분이 없는 상태라서 크롬브라우저에서 자체적으로 판단하여 div 를 삽입하면서 map, area 태그를 지우는것 같습니다.
img, map, area 태그를 삽입할때 p 태그로 한번 감싸서 삽입하시면 p 태그에 정렬이 적용되어 map, area 가 사라지지 않습니다.
```html
<p>
  <img src="test.jsp" usemap="#T1">
  <map name="T1">
    <area>
  </map>
</p>
```
