### ISSUE TITLE
안녕하세요 연결 관련 문의입니다. 

### ISSUE THREAD

**Issue by awesomejang** [naver/smarteditor2#187]
안녕하세요 스마트에디터를 사내 인트라넷에 적용하려 하는데'
인트라넷이 자체 망을 사용하고 있어 인터넷망 연결없이도 사용하는데 문제가 없는지 질문드리고 싶습니다.

**Comment by kyungilpark** [comment]
자체 리소스만 사용하기 때문에 사내 인트라넷 서버에 설치하셔서 인터넷망 연결없이 사용하실 수 있습니다.
