### ISSUE TITLE
JSP 에서 적용문제

### ISSUE THREAD

**Issue by Jihong04** [naver/smarteditor2#188]
JSP에서 적용해서 쓰려고 하니 HTML 한글이 깨지네요
인코딩도 다 UTF-8로 되어있는데
기존 프로젝트 세팅을 타면 한글이 안깨지긴 하는데
HTML 환경세팅을 바꿔보려고 건드리면 에디터가 안나오더라고요
방법이 없을까요?

**Comment by jaymz9634** [comment]
html 문서에 unicode BOM 추가해 보세요.
