### ISSUE TITLE
웹 폰트 적용 시 " 문자열이 &quot; 로 치환되는 문제

### ISSUE THREAD

**Issue by tommy-gilbut** [naver/smarteditor2#191]
웹 폰트 적용 시 HTML 탭을 보면 다음과 같이 " 문자열이 `&quot;`로 자동 치환됩니다.
`<span style="font-size: 32px; font-family: &quot;Nanum Pen Script&quot;;">`

그래서 저장하고 나면 웹폰트가 적용이 안됩니다.
혹시 자동 치환을 중단하는 옵션이 있는지요?
아니면 웹폰트 적용 방법에 대한 가이드가 있을지요?

답변 부탁드립니다. 감사합니다.

**Comment by kyungilpark** [comment]
웹폰트를 적용을 어떤식으로 구현하셨을까요?
innerHTML 로 삽입시 태그 속성안에 있는 쌍따옴표는 `&quot;` 로 변환됩니다.
쌍따옴표 대신 홑따옴표로 삽입해보시면 어떨까요?
```js
<span style="font-size: 32px; font-family: 'Nanum Pen Script';">
```

**Comment by tommy-gilbut** [comment]
웹폰트는 아래 링크대로 구현했습니다.
https://github.com/naver/smarteditor2/issues/45#issuecomment-338527828

말씀하신 대로 직접 태그를 수정하여 홑따옴표로 저장하면 잘 됩니다.
그런데 editor 창에서 입력한 내용 그대로 저장하면 쌍따옴표로 저장됩니다. 그래서 웹폰트 태그 적용이 안되구요.

혹시 웹폰트 적용 시 홑따옴표로 적용하는 옵션이 있을까 해서 여쭤봤습니다.
