### ISSUE TITLE
2.10 버전 설치

### ISSUE THREAD

**Issue by qodmsquf13** [naver/smarteditor2#192]
경로와 함수 모두 제가볼떄 오류가 없는데 모든 브라우저에서 설치가 안됩니다.
파일 두개 경로는 아래와 같습니다. 
E:\xampp\htdocs\severfile\Regame\php\write\se2\SmartEditor2Skin.html
E:\xampp\htdocs\severfile\Regame\php\write\se2\js\service\HuskyEZCreator.js
    <script type="text/javascript" src="se2/js/service/HuskyEZCreator.js" charset="utf-8" defer="defer"></script>    
    <script type="text/javascript" defer="defer">
        var oEditors = [];
        nhn.husky.EZCreator.createInIFrame({
         oAppRef: oEditors,
         elPlaceHolder: "ir1",
         sSkinURI: "se2/SmartEditor2Skin.html",
         fCreator: "createSEditor2"
        });
    </script>
    <textarea name="ir1" id="ir1" rows="10" cols="100"></textarea>
뭐가 문제인지 알려주세요. 지금 대학교 프로젝트로 이미지 게시판을 개발해야하는데 많이 어렵습니다.

**Comment by kyungilpark** [comment]
에러라도 남겨주셔야 뭔가 조언을 드릴텐데...
문의하신지 오래되서... 혹시 해결하셨나요?
