### ISSUE TITLE
스마트에디터 ONE 을 사용하고 싶은데 사용할수 있나요?

### ISSUE THREAD

**Issue by billionpjh** [naver/smarteditor2#195]
스마트에디터 ONE 을 사용하고싶은데 사용할수 있나요?
예를 들어 무료 API 라던지
상용라이센스라던지 

이런식으로 사용하고싶어 문의 남깁니다.

**Comment by kyungilpark** [comment]
올해 스마트에디터 ONE 의 상품화를 검토하였으나 아쉽게도 보류되었습니다.
때문에 향후 외부 오픈에 대한 계획이 불투명한 상태입니다.

**Comment by mungyuchoi** [comment]
아직도 보류인가요? 스마트 에디터 ONE을 너무나 사용하고 싶습니다. html, css, js
