### ISSUE TITLE
보안

### ISSUE THREAD

**Issue by Nahyun-Park** [naver/smarteditor2#197]
XSS 보안 패치 됐나요?

**Comment by kyungilpark** [comment]
어떤 보안패치를 말씀하시는지요?

**Comment by Nahyun-Park** [comment]
XSS요

**Comment by kyungilpark** [comment]
보안 패치 내역을 확인하고 싶으시면 [CHANGELOG](https://github.com/naver/smarteditor2/blob/master/CHANGELOG.md) 참고하시기 바랍니다.
