### ISSUE TITLE
스마트에디터 ONE 이나 3.0 버전은 외부사이트에서 사용할 수 없나요?

### ISSUE THREAD

**Issue by soyoudd** [naver/smarteditor2#199]
안녕하세요.
이번에 저희회사에서 개발중인 웹사이트에
네이버 스마트에디터를 적용하려고 합니다.

검색해보니, 2.0 버전은 공개되어 있는데,
3.0 이나 ONE 은 아닌것 같네요?

외부 사이트에선 2.0 만 사용 가능한지 문의드립니다.

**Comment by kyungilpark** [comment]
넵 아쉽지만 3.0 이나 ONE 은 오픈소스화 계획이 아직 없습니다.
2.0 만 사용 가능합니다.
