### ISSUE TITLE
스마트에디터2에 placeholder 적용법 여쭤봅니다.

### ISSUE THREAD

**Issue by HwangAYoung** [naver/smarteditor2#200]
아무리 알아봐도 모르겠어서 질문글납깁니다 ㅠㅠ

**Comment by kyungilpark** [comment]
input 이나 textarea 에 있는 placeholder 속성과 동일한 기능을 말씀하시는건가요?
현재 스마트에디터2 에는 해당 기능이 없습니다. 별도 구현하셔야 합니다.
