### ISSUE TITLE
스마트에디터 지원 os문의

### ISSUE THREAD

**Issue by ghost** [naver/smarteditor2#201]
우분투는 지원하지 않나요?
우분투 환경에서 사용할 수 있는 방법은 없을까요?

**Comment by kyungilpark** [comment]
특별히 OS 제약이 있는 것은 아니지만 우분투 환경에 돌려보지 않아서 정확히 어떤 부분을 말씀하시는 건지 잘 모르겠습니다.
1. 우분투에서 스마트에디터 소스파일이 빌드되지 않는다는 얘기일까요?
2. 아니면 우분투의 브라우저에서 스마트에디터 페이지가 동작하지 않는다는 얘기일까요?
