### ISSUE TITLE
SE_pasteHandler is not a constructor 에러 입니다 ..

### ISSUE THREAD

**Issue by gutenLEE** [naver/smarteditor2#202]
Uncaught TypeError : nhn.husky.SE_PasteHandler is not a constructor 
       at window.createSEditor2 (SE2BasicCreator.js:75)
       at HTMLFrameElement. <anonymous> (HuskyEZCreator.js:104)

에러메세지입니다 . 도통 모르겠네요..

**Comment by hongchii** [comment]
저도 같은 문제로 고생하고 있습니다.. 해결하시면 알려주세요..

**Comment by kyungilpark** [comment]
`SE_PasteHandler` 플러그인이 포함된 파일이 누락된 것 같은데요...
skin 페이지에 링크된 JS 파일 확인해보시기 바랍니다.
