### ISSUE TITLE
iframe 내에서 SmartEditor2를 사용했을때 발생하는 발생하는 문제

### ISSUE THREAD

**Issue by HaDdaeng** [naver/smarteditor2#203]
안녕하세요.

iframe내에서 SmartEditor2를 사용하려고 하는데 cross-origin 에러가 발생합니다.

화면 구성을 말씀드리면

A.jsp에서 iframe으로 다른 B.jsp를 호출하고 (jsp는 폴더가 다를뿐 같은 컨테이너 안에 있습니다.)

B.jsp에서 SmartEditor2를 호출하고 있습니다.

메인도메인은 main.co.kr 이지만

접속도메인은 sub.main.co.kr 형태입니다.

해결할수 있는 방법이 있을까요?

**Comment by kyungilpark** [comment]
[same-origin policy](https://developer.mozilla.org/ko/docs/Web/Security/Same-origin_policy) 에 의해 서브도메인인 경우도 기본적으로 접근이 제한됩니다.

대신 상위도메인이 같을 경우에 한해 [상위도메인으로 강제 세팅](https://developer.mozilla.org/ko/docs/Web/Security/Same-origin_policy#출처_변경)하여 통신이 가능하도록 할 수 있습니다.
```js
document.domain = "main.co.kr";
```

**Comment by HaDdaeng** [comment]
> [same-origin policy](https://developer.mozilla.org/ko/docs/Web/Security/Same-origin_policy) 에 의해 서브도메인인 경우도 기본적으로 접근이 제한됩니다.
> 
> 대신 상위도메인이 같을 경우에 한해 [상위도메인으로 강제 세팅](https://developer.mozilla.org/ko/docs/Web/Security/Same-origin_policy#%EC%B6%9C%EC%B2%98_%EB%B3%80%EA%B2%BD)하여 통신이 가능하도록 할 수 있습니다.
> 
> ```js
> document.domain = "main.co.kr";
> ```

**Comment by HaDdaeng** [comment]
> [same-origin policy](https://developer.mozilla.org/ko/docs/Web/Security/Same-origin_policy) 에 의해 서브도메인인 경우도 기본적으로 접근이 제한됩니다.
> 
> 대신 상위도메인이 같을 경우에 한해 [상위도메인으로 강제 세팅](https://developer.mozilla.org/ko/docs/Web/Security/Same-origin_policy#%EC%B6%9C%EC%B2%98_%EB%B3%80%EA%B2%BD)하여 통신이 가능하도록 할 수 있습니다.
> 
> ```js
> document.domain = "main.co.kr";
> ```

SmartEditor2에서 사용하는 모든 html에 document.domain = "main.co.kr" 을 적어주었으나 여전히 cross-origin이 발생하고 있습니다.

다른 해결 방법은 없을까요?

**Comment by kyungilpark** [comment]
개발자도구 열어보시면 cross-origin이 오류 메시지가 나오니 참고하여 설정하시기 바랍니다.
정확히 어떤 페이지끼리 cross-origin이 발생하는지 알 수 없어서 조언드리기 어려우니 SmartEditor2 의 html 뿐 아니라 A.jsp, B.jsp 모두 도메인 설정해보시기 바랍니다.
또한, 프레임간 통신하는 스크립트가 실행되기 전에 도메인이 동일하게 설정되어 있어야 하는 점 참고바랍니다.
