### ISSUE TITLE
한글 파일에서 복사하여 에디터에 붙여 넣을 때 html태그에 대해 문의드립니다.(hwpEditorBoardContent)

### ISSUE THREAD

**Issue by caramel425** [naver/smarteditor2#204]
안녕하세요, 네이버 스마트 에디터2.0 사용하고 있습니다.

한글2020 버전 사용하고 있는데 한글에서 내용을 작성하고 복사해서 웹 에디터로 붙여넣은 후 html탭으로 확인해보면

첨부파일 사진과 같이 너무 많은 태그가 붙어 이용에 불편함이 있습니다.

html태그를 최소화 하여 붙여넣을수 있는 방법이 있을까요?

텍스트로 붙여넣고 에디터에서 글자크기, 색 등을 수정하기에는 너무 양이 많아서 불가능할 것 같습니다.

답변 부탁드립니다. 감사합니다.

![html태그](https://user-images.githubusercontent.com/63336994/104278687-57623100-54ec-11eb-9fb1-e4785fa1d035.jpg)

**Comment by kyungilpark** [comment]
타프로그램(한글/워드등)에서 복사/붙여넣기하는 경우 OS레벨의 클립보드를 통해 내용이 전달되는데 클립보드에 HTML내용을 담는 주체가 타프로그램(한글/워드등)입니다.
현재 스마트에디터2에는 클립보드에서 붙여넣어지는 내용을 별도 컨버팅이나 필터링하는 기능이 포함되어있지 않습니다.
복/붙시 컨버팅/필터링이 필요하시면 [플러그인가이드](http://naver.github.io/smarteditor2/user_guide/3_customizing/plugins/)를 참고하여 기능을 추가하시기 바랍니다.

**Comment by caramel425** [comment]
빠른답변 감사합니다. 도움이 되었습니다.
