### ISSUE TITLE
Cannot read property of 'parentNode' 질문입니다.

### ISSUE THREAD

**Issue by moraedev** [naver/smarteditor2#207]
안녕하세요. 웹페이지 개발을 공부하고 있는 학생입니다.
연습삼아서 네이버 스마트 에디터를 이용하고 플러그인을 별개로 추가한, 게시판 사이트를 만들어 보려고 했는데
GitBook에 있는대로 HuskyEZCreator.js를 불러오자 해당 오류가 발생합니다.
브라우저는 엣지를 쓰고 있고 에디터는 최신 버전을 사용하고 있습니다.
너무 기본적인 질문이라 죄송합니다 ㅠㅠ.

**Comment by kyungilpark** [comment]
오류가 발생하는 위치를 알아야 정확히 답변드릴수 있을것 같은데요...

일단 유추해보자면 `elPlaceHolder` 를 찾지 못해서 해당 오류가 발생하는게 아닌가 싶습니다.
https://github.com/naver/smarteditor2/blob/cf6070f1cd68a3ce35852e4b46e005b7b80978cd/workspace/static/js/service/HuskyEZCreator.js#L78
초기화시에 지정한 `elPlaceHolder` 에 해당하는 Element 가 존재하는지 확인바랍니다.
https://github.com/naver/smarteditor2/blob/cf6070f1cd68a3ce35852e4b46e005b7b80978cd/workspace/static/SmartEditor2.html#L28-L30

**Comment by moraedev** [comment]
아 된거같아요. 어딘가 제가 오타를 몇 썼나봐요.
감사합니다!
