### ISSUE TITLE
모바일에서 사용이 불가능한가요?

### ISSUE THREAD

**Issue by 100milliongold** [naver/smarteditor2#22]
모바일에서 사용하기위해서 css 를 변경하는 편법도 있지만 높이에 따라 스크롤이 안되는 문제가 있습니다.

모바일에서도 사용가능한 방안이 없을까요?

**Comment by kyungilpark** [comment]
안녕하세요

모바일에서 기능이 정상동작하는지 여부는 태블릿에서 점검한 바가 있어 사용은 가능하실겁니다.
다만 모바일용 전용스킨을 제공하지 않아 불편하시겠지만 모바일에 최적화된 UI로 마크업/css 스킨을 직접 구성하셔야 합니다.

그리고 iOS에서 iframe이슈가 많아 `SmartEditor2.html`보다는 `SmartEditor2noframe.html`를 사용해서 UI구성하시는 걸 추천드립니다.

**Comment by gadian88** [comment]
SmartEditor2noframe.html

을 쓰니 잘됩니다! 감사해요

**Comment by gadian88** [comment]
모바일에서 테스트 했더니 똑같이 깨져서 나옵니다.

좋은 방법 없을까요???
