### ISSUE TITLE
Bower 지원

### ISSUE THREAD

**Issue by vingorius** [naver/smarteditor2#24]
TODO 목록에 있던데...Bower 지원 부탁드립니다.

**Comment by kyungilpark** [comment]
일에 치여 트렌드를 못따라가고 있었는데 bower 가 deprecated 되었군요.. ㅠ.ㅠ
- https://www.npmjs.com/package/bower
- https://snyk.io/blog/bower-is-dead/

**Comment by kyungilpark** [comment]
deprecated 되어 지원하지 않고 이슈 닫습니다.
