### ISSUE TITLE
네이버 에디터 2.0 하이퍼링크 밑줄 해제 설정 방법이 따로 있나요?

### ISSUE THREAD

**Issue by cbw1030** [naver/smarteditor2#246]
안녕하세요. 네이버 에디터 2.0을 사용하고 있는 유저입니다.

어떤 텍스트에 하이퍼링크를 걸면 자동으로 아래 첫 번째 사진처럼 밑줄이 적용되어 있습니다.

저 상태에서 글을 등록하면 아래 두 번째 사진처럼 텍스트에 밑줄이 적용되어 있지 않은 상태에서 글이 등록됩니다.

텍스트에 하이퍼링크를 걸었을 때 자동으로 적용되는 밑줄 버튼을 클릭해도 해제가 되지를 않습니다.

1. 하이퍼링크를 걸었을 때 눌려있는 밑줄 버튼을 해제할 수 있는 설정을 어디서 할 수 있나요?
2. 1번 설정이 없다면 밑줄 버튼이 눌려있는 상태에서 글을 등록했을 때 적용되지 않는 이슈를 어떻게 해결할 수 있을까요?

* 글을 등록하기 전
![image](https://user-images.githubusercontent.com/40957996/134604284-546891a3-c5db-431e-b9a3-4400c1f3e49c.png)

* 글을 등록한 후
![image](https://user-images.githubusercontent.com/40957996/134604430-e7b555d1-8c74-4967-95d8-15744f1fd5ab.png)

**Comment by kyungilpark** [comment]
@cbw1030 님
SE2 에서 하이퍼링크 지정시 브라우저 기본스타일로 적용됩니다.
글 등록 후 뷰어에서 하이퍼링크 밑줄이 노출되지 않는 것은 뷰어쪽 페이지의 CSS 에서 하이퍼링크에 대한 CSS스타일을 별도로 지정하셔서 그런것 같습니다.
뷰어 CSS스타일 확인하시기 바랍니다.
