### ISSUE TITLE
자동 div 추가 밑 p 태그 추가  막을순 없나요?

### ISSUE THREAD

**Issue by neweve1004** [naver/smarteditor2#25]
처음 글을 작성할때는 상관이 없는데 db에서 내용을 가져온 후 따로 내용을 수정하지않고
에디터에 써진 내용을 다시 가져와서 확인해보면 처음 내용을 div태그로 감싸고 
p태그가 추가되어집니다.. 이때 p태그가 추가된걸 그대로 db에 저장해서 다시 호출하니
<p>?</p> 로 나오더군요..

이래저래 확인해보면 db내용을 에디터에 추가하면 커서가 우선 자동 개행되는데 그때 p태그가 추가
되고 그대로 바로 db에 저장을 다시 하면 <p>?</p> 이렇게 저장되는거 같습니다.

자동으로 div태그생성과 자동개행으로 생기는 p태그를 안생기게 하고싶은데 어떻게 해야하나요?

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
