### ISSUE TITLE
스마트에디터2 이미지 파일 첨부시

### ISSUE THREAD

**Issue by Shon86** [naver/smarteditor2#258]
<img 태그로 인하여 네트워크 에러 406이 발생합니다.

로컬이나 개발서버에서는 정상 작동하는데 운영서버에서만 해당 에러가 발생하네요.

서버 설정법이라든가 공유 부탁드립니다.

**Comment by kyungilpark** [comment]
<img 는 기본 서버설정으로 정상동작하기 때문에 별도 가이드는 없습니다.

406 응답을 주는 것은 해당 서버에서 특정 content-type 에 대해 막아놓았을 가능성이 있습니다.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406

image 등에 대한 MIME_type 이 막혀있는건 아닌지 확인바랍니다.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept
