### ISSUE TITLE
에디터 2.0 버전 서비스 종료 문의 

### ISSUE THREAD

**Issue by heyjin90** [naver/smarteditor2#262]
블로그를 통해 스마트 에디터 2.0 버전이 11월 종료된다는 내용을 확인하였습니다. 

네이버 블로그에서만 사용이 중단되는 것인지, 오픈소스 2.0 버전도 서비스 종료되는 것인지 궁금합니다.  
서비스 종료된다면 다른 버전 오픈소스 계획이 있으신지 문의 드립니다.

**Comment by kyungilpark** [comment]
@heyjin90 님
안녕하세요~
본 github 의 smarteditor2 는 네이버서비스 디펜던시가 제거된 오픈소스 버전입니다.
네이버블로그 서비스용 smarteditor2 종료와는 상관없습니다.

smarteditor2 오픈소스버전은 회사차원의 지원이 없기 때문에 개인적으로 시간을 할애해야 하는 어려움이 있어 오래전부터 유지보수가 중단되다시피된 상태입니다.
사용하는데 문제가 없으시다면 그대로 사용하셔도 무방합니다.

현재 다른 버전 오픈소스 계획은 없습니다.

감사합니다.
