### ISSUE TITLE
3.0은 언제 오픈소스화 되거나 할 계획이 있는지 알수 없나요??

### ISSUE THREAD

**Issue by devkan** [naver/smarteditor2#265]
스마트에디터 2까지만 오픈되어 있는데..
3은 언제쯤 오픈소스화 계획이 있는지 궁금합니다.
아니면.. 아예 계획이 없다거나 계획은 있는지가 궁금합니다.

알려주시면 감사하겠습니다.

**Comment by kyungilpark** [comment]
@devkan 님
현재 SE3 이후 버전은 오픈소스계획이 없습니다.
감사합니다.
