### ISSUE TITLE
이미지 태그 삭제

### ISSUE THREAD

**Issue by JinSeok-Ryu** [naver/smarteditor2#27]
안녕하세요.
현재 스마트 에디터를 잘 사용중에 있습니다. ㅎㅎ
근데 이번에 추가 해야할 부분이 생겨서 질문 드립니다.
제가 스마트 에디터 상에서 이미지를 업로드 할때 본문에도 이미지가 삽입되고
따로 리스트를 만들어서 업로드한 이미지를 하나씩 볼 수 있게 하고 있는데요.
여쭤보고 싶은건 본문상에서가 아닌 리스트에서 이미지를 삭제할때 본문상에서도 하고 싶어서요.
해당 이미지 태그를 지워주면 될듯한데. 감이 잘 안잡히네요.
스마트 에디터 기능 중 찾아 바꾸기를 이용하려고 했는데 그것도 잘 안되구요..
그리고 이 반대도 가능할지 싶네요.
본문상에서 이미지를 지우면 이미지 명을 받아온다던가 해서 리스트에서 지울수 있게요.
이미지 명만 받아오면 가능할텐데... 아직 많이 부족합니다. ㅜ.ㅠ

**Comment by imredcat** [comment]
저도 그부분을 찾고 있었는데요. 
제가 구현한 부분의 흐름은...
업로드된 이미지 목록과 본문내의 이미지를 매칭시킬 class 값을 동일하게 해서 등록 합니다.
예 이미지목록에 삭제 버튼에는 
< input type='button' value='삭제' imgcls='image_class_in_editor' onclick='delImg(this)'>
본문 내용에 이미지를 삽입할때는
< img src='...' class='image_class_in_editor'>
이런식으로 넣어서 삭제 버튼의 imgcls 값을 본문 html값에서 찾아서 해당 이미지 태그 삭제 하고
다시 html을 적용하는 방식입니다.
그런데...
예전에는 php 업로더 예제에 해당 플러그인이 포함 되어 있어서 쉽게 처리 할 있었습니다.
만약 업로드예제(photo_uploader 폴더)가 있다면 
`oEditors.getById[edit_txtid].exec("REMOVE_INN_IMG", [o.val(),imgcls]);`
이런 식으로 가능했습니다.
지금 버전에서는 해당 예제가 없어져서 이전 버전의 플러그인을 가져와 사용하시거나,
아래 코드를 응용하시면 될 듯 합니다.

function deltInnerImg(obj){
       imgcls = $(obj)attr("imglcs");
	sContents = oEditors.getById[edit_txtid].getContents();
	ptn = eval('/<img [^<]*'+imgcls+'[^>]*>/gi');
	sContents = sContents.replace(ptn, "");
	oEditors.getById[edit_txtid].setContents(sContents);
	$(obj).remove();
}

**Comment by imredcat** [comment]
그리고... 
2.8버전에 있는 photo_uploader 예제를 이용하시는 거라면 
photo_uploader/plugin/hp_SE2M_AttachQuickPhoto.js 파일의
137번 줄 `$ON_REMOVE_INN_IMG:function (imgsrc) {`를 
`$ON_REMOVE_INN_IMG:function (imgsrc,imgcls) {`로 수정 하셔야 할겁니다.

**Comment by JinSeok-Ryu** [comment]
으 말씀하신 내용을 못보고 indexOf 를 이용해서 해결했습니다.
말씀하신 deltInnerImg 펑션을 보니 전 왜 저런생각을 못했을까 싶네요 ㅋ
감사합니다!!! ^^
