### ISSUE TITLE
스마트에디터 ONE 이나 3.0 버전은 외부사이트에서 사용할 수 없나요? 

### ISSUE THREAD

**Issue by chlgbdud** [naver/smarteditor2#271]
https://github.com/naver/smarteditor2/issues/199

이 글에선 2만 오픈소스라고 하던데 현시점도 마찬가지인지 궁금합니다.

**Comment by kyungilpark** [comment]
넵 아쉽지만 오픈소스 계획이 없습니다.

**Comment by chlgbdud** [comment]
답변 감사합니다
