### ISSUE TITLE
textarea 내용 수정 문의

### ISSUE THREAD

**Issue by Hazel-K** [naver/smarteditor2#274]
스마트에디터로 변환된 textarea 태그 내부의 전체 내용 중, 일부를 readonly, disable처럼 수정할 수 없게 하고 원하는 부분만을 수정/입력할 수 있게 하는 기능을 구현할 수 있을까요?

![image](https://user-images.githubusercontent.com/59563487/232722293-80104298-0459-43d8-940b-16209d04c931.png)
이를 테면 위와 같은 상황에서, '가 나'는 삭제 및 수정이 불가능하게 하고, '다'는 수정처리가 가능하게끔 처리를 할 수 있는지가 궁금합니다.
(오로지 에디터 내 textarea에서 내용 입력 중의 상황을 두고 하는 이야기입니다.)

사용자분의 요청이 있어 가능 불가능의 여부를 확실히 남기고 싶어서 문의드립니다. 감사합니다.

**Comment by kyungilpark** [comment]
브라우저에서 textarea 영역전부를 하나의 입력영역으로 판단하기 때문에 일부텍스트만 readonly, disable 상태로 만들 수 없습니다.
