### ISSUE TITLE
이미지 파일명을 DB에 넣고 싶어요.

### ISSUE THREAD

**Issue by kakera87** [naver/smarteditor2#28]
현재 스프링+마이바티스를 이용해 프로젝트를 만드는 중입니다.

지식이 너무 부족하여
http://roqkffhwk.tistory.com/202
이 블로그를 참고(거의 배끼듯)하여 게시판을 만들고 있습니다.

사진이 정상적으로 서버 upload폴더에 저장되었고
그 후, 에디터 상에 업로드된 파일이 표시되는 것도 정상적으로 이루어졌고
jsp파일내부에 content(textarea 이름) 내부에 작성된 text도 DB에 정상적으로 적용이 잘되었습니다만

업로드된 이미지파일명을 VO 객체에 담아서 DB로 보내고 새로 만들어질 view파일에서 불러올 생각입니다.

DB에 저장될 파일이름을 어디서 어떻게 구해와야할지 몰라서 3일째 고민중인데 도움좀 부탁드립니다.

**Comment by Seungcheol-Lee** [comment]
어떤 기능을 구현하려고 하시는지 잘 감이 안잡히는데요
일단 photo_uploader로 업로드한 이미지명은 textarea(에디터) 상에 img 태그로서 삽입되는 방식이니
1. 파일 정보를 DB에 저장할때 게시물의 정보가 필요하지 않다면 file_uploader 컨트롤러에서 직접 파일 정보의 VO를 생성하여 DB에 저장
2. text가 DB에 저장되는 시점에 Jsoup 과 같은 HTML Parser로 전체 text를 HTML Document 데이터구조로 파싱한 뒤 img 태그만 골라서 src 속성의 값을 (필요시 substring을 이용하여 파일명 부분만 따로 뽑아내어) VO 에 저장한 뒤 따로 DB에 저장

이정도 방법이 있을 것 같습니다.

**Comment by imredcat** [comment]
위2번항과 유사하게 업로드하고 본문에 이미지가 표시 되는 시점에 본문 form에 이미지정보 hidden 필드 추가하여 submit 시 디비에 저장하는 방법이 있습니다. 
2번과 마찬가지로 물론 text를 파싱해서 본문에 없는 이미지를 걸러내야 합니다.

**Comment by kakera87** [comment]
감사합니다 덕분에 잘처리했습니다.
