### ISSUE TITLE
폰트 저작권

### ISSUE THREAD

**Issue by Ppakgyeon** [naver/smarteditor2#283]
해당 라이브러리로 웹페이지를 제작하여 화면에 출력시 돋움이나 기본 폰트 등이 상용적으로 저작권에 문제가 없는지 궁금합니다.

**Comment by kyungilpark** [comment]
스마트에디터를 통해 생성된 HTML 은 특정 텍스트영역을 어떤 폰트패밀리로 표현할 것인지만 지정해줄뿐 폰트파일을 복제하거나 직접적으로 사용하지는 않습니다. 때문에 폰트 저작권과는 무관한 것으로 알고 있습니다.

정확한 내용은 저작권전문변호사분과 상담바랍니다.
