### ISSUE TITLE
<> 태그 삽입 자동으로 변경안되게???

### ISSUE THREAD

**Issue by netstar7** [naver/smarteditor2#29]
안녕하세요.

스마트에디터(Version: 2.9.0.4a256db)에서 
글작성할때 <안녕하세요>태그를 넣으면 html탭에는 \&lt;안녕하세요\&gt;로 들어가 있는데..

저장하면 <안녕하세요>로 바뀌어 버리네요.
\&lt;안녕하세요\&gt; 이대로 db에 저장하는 방법은 없을까요???

감사합니다.

**Comment by kyungilpark** [comment]
html탭에서 `&lt;안녕하세요&gt;`로 나온다면 에디터자체에서는 그 데이터 그대로 반환합니다.
서버로 전송하기전에 JS에서 변환하는 부분이 없는지 혹은 서버측에서 받으면서 필터링하는 부분이 없는지 확인부탁드립니다.
