### ISSUE TITLE
정렬을 하는데 ""가 안붙어요..

### ISSUE THREAD

**Issue by jiyeon0901** [naver/smarteditor2#32]
글자정렬에서 오른쪽정렬, 왼쪽정렬,가운데정렬,양쪽정렬을 하면요

 style="TEXT-ALIGN: left" align=left>왼쪽
 style="TEXT-ALIGN: center" align=center>가운데
 style="TEXT-ALIGN: right" align=right>오른쪽
 style="TEXT-ALIGN: justify" align=justify>양쪽

소스로 인식해서 P태그는 지울게요

이렇게 align에 ""가 없이 html 소스가 되는데.. 이게 웹접근성에 걸려서요.. 수정을 하려면 어디서 수정을 해야 할까요?

**Comment by kyungilpark** [comment]
안녕하세요
글작성된 내용을 최종으로 저장할때 innerHTML을 사용하는데 IE8이하에서는 element속성에 공백이 없는 경우 따옴표가 생략되어 반환됩니다.
때문에 저장시점의 컨텐츠를 확인하여 정규식으로 element에 따옴표가 생략된 속성값을 변환해주어야 할 것 같습니다.
