### ISSUE TITLE
IE에서 셀을 드래그 했을때 셀 선택이 안됩니다.

### ISSUE THREAD

**Issue by ymy9824** [naver/smarteditor2#34]
크롬이나 엣지 등에서는 동작하는데 IE에서 셀 선택이 안되어서 병합이나 색상 지정을 할수가 없습니다.
IE에서도 스마트에디터 데모페이지에서는 셀 선택이 동작하지만 제가 설치한 페이지에서 동작하지 않고 네이버 블로그에서도 테스트 해 본 결과 셀 선택이 되지 않는것 같습니다.

**Comment by kyungilpark** [comment]
저는 재현되지 않는데요 ㅠ.ㅠ
어떤 IE버전에서 어떤 경우에 재현되는지 좀 더 자세하게 알려주시면 감사하겠습니다.
