### ISSUE TITLE
하이퍼 링크에 대한 A 태그 자동 삽입 이슈 문의

### ISSUE THREAD

**Issue by liljay** [naver/smarteditor2#35]
안녕하세요.

1. 버전 정보
 - SmartEditor 2.3.10.O11329

2. 이슈 내용

![1](https://user-images.githubusercontent.com/6614194/27824201-9d31e61a-60e6-11e7-831e-3d4d91a007cd.PNG)

HTML 탭에서 자바스크립트 코드에 http://www.google-analytics.com/analytics.js라는 URL을 넣은 후
Editor 탭을 누른 후 저장 하였습니다. 

![3](https://user-images.githubusercontent.com/6614194/27824216-ab44f5b2-60e6-11e7-8122-6e8172d344b6.PNG)

저장 후 확인 결과 입력한 URL을 a 태그로 감싸도록 자동으로 처리가 되었는데요.

<a href="http://www.google-analytics.com/analytics.js">http://www.google-analytics.com/analytics.js</a>

혹시 해당 기능에 대해 끌 수 있는 옵션이 있는지 혹은 해결 방법이 있는지 답변 부탁 드리겠습니다.

감사합니다.

**Comment by kyungilpark** [comment]
보안상 스크립트태그를 직접넣는 것은 권장하지 않습니다.
2.3.10 버전이라면 설정파일(`SE2B_Configuration_Service.js`)에서 옵션 변경하시면 됩니다.
```js
nhn.husky.SE2M_Configuration.SE2M_Hyperlink = {
	bAutolink : false	// 자동링크기능 사용여부(기본값:true)
};
```

**Comment by liljay** [comment]
해당 기능의 옵션을 false로 변경 후 테스트 결과 정상 동작 됩니다.
도움을 주셔서 정말 감사 드립니다.
