### ISSUE TITLE
특정 browser 에서 jindo 프레임웍 관련 문제가 있어 문의 드립니다. 

### ISSUE THREAD

**Issue by Jiyeong** [naver/smarteditor2#37]
게시판에 에디터를 적용하여 개발 중입니다.
한 화면에서 최초 글쓰기/수정모드에서 작성/게시글 상세조회를 한번에 하게되어서
에디터 부분을 숨겼다 보였다 하는 기능을 넣었습니다. 
또한 파일도 여러건 upload 하는 기능도 추가 중입니다. 

크롬에서는 에디터가 모두 잘 뜨지만, 익스플로러(11ver) 에서 수정모드로 이동시 에러가 나고 에디터를 볼 수 없습니다. 글쓰기 모드에서는 잘 보입니다.

jindo_component.js
jindo2.all.js
jindo.min.js

위 js 파일을 모두 js/lib 파일에 넣어보았지만 같은 오류가 납니다. 

제발 ㅠ꼭 확인 부탁드립니다. ㅠ

**Comment by kyungilpark** [comment]
어떤 에러가 나는지 알수없는 상황에서 뭐라고 말씀드리기 어렵네요..
에러메시지 확인 가능할까요?

**Comment by Jiyeong** [comment]
안녕하세요, 지금은 문제를 해결하여 완료했습니다~
웹화면 resizing 하면서 문제가 있던 것이어서 수정했습니다. 
답신 감사합니다^^
