### ISSUE TITLE
익스에서 주석 변환 제대로 처리 안됨.

### ISSUE THREAD

**Issue by anewjump** [naver/smarteditor2#38]
이 문제는 크롬에서는 제대로 동작하지만, 익스에서는 처리가 제대로 안됩니다.
스마트에디터를 html 상태로 놓고, 다음 글은 문제 없이 입력이 됩니다.

```
<table>
  <tbody>
    <tr><td>
       <!-- 이런주석 가능-->
       하하하
    </td></tr>
</tbody>
</table>
```
그런데 아래와 같이 태그 안에 주석의 내용을 태그로 넣으면 처리가 안됩니다.
```
<table>
  <tbody>
    <tr><td>
      <!-- <p>이런주석 불가</p> -->
      하하하
    </td></tr>
  </tbody>
</table>
```
위의 안되는 주석은 크롬에서는 잘 동작합니다만,
익스 11에서는 잘 되지 않습니다.
어떤 문제 일까요?

**Comment by kyungilpark** [comment]
어떤게 안된다는 말씀이신지 잘 모르겠어요 ㅠ.ㅠ
사용하시는 스마트에디터 버전이 어떻게 되나요?

**Comment by anewjump** [comment]
아 제가 그누보드5에 적용된 스마트에디터의 증상을 적은것인데.. 이게 그누보드의 문제인지 스마트에디터의 문제인지 정확히 모르겠습니다. 나름 해결을 해본 뒤 결과를 다시 포스팅 하도록 해보겠습니다.

**Comment by anewjump** [comment]
해결했습니다. 스마트에디터 버전 Version: 2.8.2.12056 이 적용된 상태에서 안되었었는데,
Version: 2.9.0.4a256db 을 적용하고 문제점이 사라졌습니다. 관련해서 그누보드 sir 패치 5.2.9 를 사용하였습니다. 
https://sir.kr/g5_pds/3678
