### ISSUE TITLE
네이버 에디터 엔터 시 p태그

### ISSUE THREAD

**Issue by sipt222** [naver/smarteditor2#40]
안녕하세요.

네이버 스마트 에디터 사용 중입니다.

현재 textarea에 에디터 에디터를 적용해서 사용하고 있습니다.(총 3개의 textarea)

엔터를 치지 않고 값을 저장하면 <p>태그가 붙지 않는데

엔터를 치고 텍스트를 저장하면 각 줄 마다 <p> 태그로 감싸더군요.

인터넷에 찾아봐서 

smarteditor2의 

function _setLineStyle(div, sStyleName, styleValue){
	if(!div){
		bWrapperCreated = true;

		// try to wrap with P first
		try{
			div = thisRef.oSelection.surroundContentsWithNewNode("");  <!-- 이부분(원래 "p")
		// if the range contains a block-level tag, wrap it with a DIV
		}catch(e){
			div = thisRef.oSelection.surroundContentsWithNewNode("DIV");
		}
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * @pluginDesc Enter키 입력시에 현재 줄을 P 태그로 감거나 <br> 태그를 삽입한다.
 */
nhn.husky.SE_WYSIWYGEnterKey = jindo.$Class({
	name : "SE_WYSIWYGEnterKey",

	$init : function(sLineBreaker){
		if(sLineBreaker == "BR"){
			this.sLineBreaker = "BR"; <!-- 이 부분? 기존 "P"
		}else{
			this.sLineBreaker = "BR";
		}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

SE2BasicCreator.js의

oEditor.registerPlugin(new nhn.husky.SE_WYSIWYGEnterKey("BR")); // 엔터 시 처리, 현재는 P로 처리

이 부분을 br로 바꾸어 줬는데 여전히 <p>태그를 감싸더군요 해결방법이 없나요??

**Comment by kyungilpark** [comment]
엔터쳤을때 `BR`을 삽입하고 싶으신거라면 다른건 건드리지 마시고
`SE2BasicCreator.js`파일에서 `SE_WYSIWYGEnterKey`플러그인 세팅을 `BR`로 지정하시면 됩니다.
```js
oEditor.registerPlugin(new nhn.husky.SE_WYSIWYGEnterKey("BR"));							// 엔터 시 처리, 현재는 P로 처리
```
