### ISSUE TITLE
tab 키 기능을 그냥 일반 한글이나 메모장처럼 \t로 구현가능할까요?

### ISSUE THREAD

**Issue by Aideln** [naver/smarteditor2#41]
tab 키 기능을 그냥 일반 한글이나 메모장처럼 \t로 구현가능할까요?
아니면 지금 들여쓰기로 되어있는 이벤트를 뺄 수 있나요?

**Comment by kyungilpark** [comment]
들여쓰기/내어쓰기로 등록되어있는 tab/shift+tab 단축키를 빼려면 내부소스를 수정하셔야 합니다.
`SE2M_ExecCommand` 플러그인에 있는 아래 코드를 주석처리하면 됩니다.
```js
this.oApp.exec("REGISTER_HOTKEY", ["tab", "INDENT"]);
this.oApp.exec("REGISTER_HOTKEY", ["shift+tab", "OUTDENT"]);
```
브라우저의 tab/shift+tab 키는 기본적으로 포커스이동으로 동작하기 때문에 `\t`삽입처리하려면 이벤트 잡아서 구현하셔야 합니다.
