### ISSUE TITLE
photo_uploader 로 첨부하면 본문에 이미지가 2개 붙습니다.

### ISSUE THREAD

**Issue by oilugi** [naver/smarteditor2#42]
alert 로 찍어봐도
opener.nhn.husky.PopUpManager.setCallback(window, 'SET_PHOTO', [oFileInfo]);
는 한번만 실행이 되는것 확인은 했습니다.
이미지를 1개 올리면 에디터창에 같은이미지 가 2개가 붙습니다.
이미지 a,b 2개 올리면 
에디터창에
a,b,a,b 이렇게 4개가 붙습니다....

**Comment by leehunkyu00** [comment]
저도 동일한 증상이 나타나서 여러가지를 시도하다가 js library전체를 최신 버전으로 교체하니깐 정상적으로 동작했습니다. 아마 예전 버전의 버그같은데 자세히 디버깅하기 보단 최신 버전으로 올리는게 좋을 것 같습니다.

js 폴더(lib  service  smar...)를 naver-smarteditor2-ee3e7ac/demo/js 으로 교체했습니다.

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
