### ISSUE TITLE
본문 글쓸때 커서위치 포커싱 이슈

### ISSUE THREAD

**Issue by arsens24** [naver/smarteditor2#44]
스마트에디터 2.0를 포함한 게시판 솔루션 '망보드'를 사용하고 있습니다.

본문 글쓸때, 커서위치에 포커싱이 되는데요.
처음에 쓸때는 좋은데, 다 쓴 이후에 확인 버튼을 누르려 하단으로 스크롤 해서 내리면..
다시 화면이 현재 커서로 포커싱되어, 두번 내려야하는 현상이 발생하고 있습니다.
해당 부분 확인 가능할까요.

영상 첨부드립니다.
https://youtu.be/pmFDceN8ses

**Comment by kyungilpark** [comment]
모바일환경의 경우 특정 기기/OS에서만 발생하는 이슈가 많아 화면만으로는 디버깅이 어렵습니다.
한글이 완성되면서 브라우저가 자동스크롤하는 것으로 추정되는데 영문의 경우에도 동일하게 재현되나요? 
재현되는 기기 및 OS버전을 알려주시면 좀 더 확인해보겠습니다.
