### ISSUE TITLE
드래그 파일 업로드

### ISSUE THREAD

**Issue by jooooda** [naver/smarteditor2#46]
드래그 파일 업로드시 업로드한 파일을 제대로 읽어들이지 못합니다.
다른 프로젝트에서 구현했을때는 해당 경로에 파일이 제대로 만들어졌는데,
현재 작업중인 프로젝트에서는 빈파일만 만들어지는데
이런 경우 어느 부분을 수정해야 되나요..?

**Comment by kyungilpark** [comment]
다른 프로젝트에서 정상동작했는데 현재 작업중인 프로젝트에서 빈파일이 만들어진 것이라면 서버쪽에 파일이 정상적으로 업로드되었는지 확인부탁드립니다.
