### ISSUE TITLE
스마트 에디터 textarea 한컴돋움 없애려면?

### ISSUE THREAD

**Issue by hanyunhu** [naver/smarteditor2#47]
스마트 에디터에서 글 작성시 자동으로  textarea 안에  한컴돋움 이 생성이 됩니다.

mso-fareast-font-family: 한컴돋움;

이것을 빼보려고 소스파일들을 보았지만 소스파일에는 없는 것 같고요.
어떻게 해야 뺄수 있을 까요?

한글은 상관이 없는데 중국어나 다른 언어 사용시 정상으로 나오지 않는것 같아서 문의 드립니다.

**Comment by hanyunhu** [comment]
아 이건 한글로 작성된 파일의 내용을 복사해서 넣었더니 자동으로 생긴거네요.
^^

**Comment by kyungilpark** [comment]
아 넵.. 복사하는 프로그램마다 HTML에 자동으로 생성되는 스타일이 있습니다.
저장시점에 정제처리하던지 붙여넣기 후에 정제처리하셔야 할 듯합니다.
