### ISSUE TITLE
다국어버젼 때문에 기존 사용중이던 스마트에디터 버젼을 업글하려하는데요

### ISSUE THREAD

**Issue by sjsjss8** [naver/smarteditor2#49]
smarteditor2-2.9.0\dist 폴더에
SmartEditor2Skin_en_US.html 페이지 라든지
SmartEditor2Skin_ja_JP.html 페이지 라든지
뭔가 번역이 많이 안되있는거 같은건 기분탓인가요?제가 잘못 받은건가요?
API가 최신버젼으로 업그레이드가 안되있는거같아서 보기가 너무 어렵네요

**Comment by kyungilpark** [comment]
누락부분 제보해주시면 #19 에서 정리하여 반영하도록 하겠습니다.
