### ISSUE TITLE
photo_uploader 보안패치 적용하려고 합니다.

### ISSUE THREAD

**Issue by todayears** [naver/smarteditor2#5]
2.8.2.3 버전에서 보안패치 된 

photo_uploader 관련 파일을 적용하고 싶은데요,

어디서 패치 된 파일을 찾을 수 있을까요?

**Comment by kyungilpark** [comment]
이전버전은 릴리즈페이지에서 다운받으실 수 있습니다.
https://github.com/naver/smarteditor2/releases/v2.8.2.3

**Comment by todayears** [comment]
@kyungilpark 
답변 감사드립니다.
많은 도움이 되었습니다!
