### ISSUE TITLE
스마트에디터 작업시 변수 설정이 가능한가요

### ISSUE THREAD

**Issue by cse96hk** [naver/smarteditor2#52]
smart_editor2_inputarea.html
 body tag---
`body  if($board_id == "online"){ onClick="goAccount();"}`
body tag ---

scrip ---
`function goAccount(){
        if( confirm("본 서비스는 결제이후 이용이 가능합니다. \n결제 페이지로 이동하시겠습니까?")){
            top.parent.location.href='/qna/consult4_1.php'; 
        }
    }`
script ---

board_id online일경우  goAccount(); 스크립트를 실행 합니다.

board_id 변수를 가져오는 방법을 조언 부탁 드립니다.

감사합니다.

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
