### ISSUE TITLE
다국어 버전 사진첨부 팝업은 다국어 적용 html없나요??

### ISSUE THREAD

**Issue by pminmin2** [naver/smarteditor2#53]
uploader.html은 수기 또는 분기로 전부 다국어 변환한다고 쳐도
import된 jindo, attach_photh.js 관련도 다국어 대상일것인데(alert 메시지 등)

관련된내용으로 처리된 다국어 파일이 있을런지요??

**Comment by kyungilpark** [comment]
사진첨부 팝업은 샘플이고 현재는 공식적으로 관리하고 있지 않아서 다국어 파일이 없습니다.
