### ISSUE TITLE
로컬 실행할때 오류가 발생합니다.

### ISSUE THREAD

**Issue by kcal2845** [naver/smarteditor2#54]
Uncaught DOMException: Blocked a frame with origin "null"  HuskyEZCreator.js:82 from accessing a cross-origin frame. 

웹에서는 문제 없는데 로컬에서 사용하려고 했는데 오류가 발생하네요.  로컬에서는 사용 불가능한가요?

**Comment by kyungilpark** [comment]
로컬에서 실행시키면 [Same-origin policy](https://developer.mozilla.org/ko/docs/Web/Security/Same-origin_policy) 때문에 브라우저자체에서 iframe 과 통신을 막아 동작하지 않을 수 있습니다.
