### ISSUE TITLE
첫줄에 글자 입력후 엔터키 입력시 폰트 크기 변경되는 현상

### ISSUE THREAD

**Issue by younjunghyun** [naver/smarteditor2#55]
에디터 최초로딩시 9pt로 설정되어 있는데 입력후
엔터키를 치면 입력한 글자가 12pt로 변경되는 경우가 종종있습니다.
혹시 어떤 원인인지 알수 있을까요?

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
