### ISSUE TITLE
스마트 에디터 PPT 도형, 화살표 관련

### ISSUE THREAD

**Issue by ezibiya** [naver/smarteditor2#57]
안녕하세요
스마트에디터 2.0을 개발에 적용하여 사용중인데요

PPT->WORD로 변환후 전제 선택하여 붙여넣기 하는데

표,그림은 잘 붙지만 도형 및 화살표는 붙질 않네요?

지원이 안되는것인가요?

**Comment by kyungilpark** [comment]
타 프로그램에서의 복/붙은 OS 레벨에서의 동작이라 제약이 많습니다.
해당 프로그램에서 지원하는 않는 것으로 보입니다.
