### ISSUE TITLE
네이버 스마트 에디터를 회사에서 사용하려고 하는데요

### ISSUE THREAD

**Issue by lonmell0213** [naver/smarteditor2#59]
일단 사용하려는 부분은 처음에는 상업적인 부분이 포함되지 않지만, 이후에는 사용될수도 있기 때문에 
상업적 이용이 가능한 범위를 알고 싶습니다.

**Comment by kyungilpark** [comment]
[LGPL v2.1](http://www.gnu.org/licenses/lgpl-2.1.html) 라이선스를 따르기 때문에 상업적으로 사용하셔도 무방합니다.
단, JS소스에 명시되어 있는 `Copyright` 문구를 제거하시면 안됩니다.
또한, 소스를 수정하여 재배포 하시는 경우라면 LGPL v2.1 라이선스를 유지해주셔야 합니다.
