### ISSUE TITLE
이미지 퀵 에디터 기능 없는건가요?

### ISSUE THREAD

**Issue by rhrh82** [naver/smarteditor2#6]
소스에는 분명 포함된것 같은데

첨부된 이미지를 눌러도 안나타 나네요.

레이어만 살아있고 관련 스크립트는 삭제되어 있나요?

단축키로 써야하나..

이미지 클릭하면 나타나는 이미지 퀵 에디터 어떻게 쓰는지 알려주세요..

**Comment by kyungilpark** [comment]
현재 이미지 퀵 에디터 기능은 현재 오픈소스로 제공되지 않습니다.
소스 분리가 제대로 안되서 마크업만 있고 스크립트는 없네요.
직접 구현하셔야 할 듯합니다.

**Comment by rhrh82** [comment]
이미 해당 기능을 일부 비슷하게나마 구현은 했습니다만..
혹시나 해서 여쭤봤습니다.
답변 감사합니다^^
