### ISSUE TITLE
툴바 툴팁이 사라집니다.

### ISSUE THREAD

**Issue by buruss** [naver/smarteditor2#60]
크롬에서 스마트에디터 툴바에 마우스를 가져다 대면 툴팁이 0.1 ~ 0.5초 정도 보이고 금방 사라집니다.
페이지 접속할 때부터 증상이 바로 발생하기도 하고, 텍스트 영역에 마우스 클릭 후부터 발생하기도 합니다.

엣지, IE, 파이어폭스에서는 이런 증상이 없습니다.

크롬 v63, v64 에서 아래 데모 페이지를 이용하여 테스트하였습니다.
http://naver.github.io/smarteditor2/demo/

스마트에디터 버전 Version: 2.9.0.4a256db

**Comment by kyungilpark** [comment]
툴바 툴팁 기능을 smarteditor2 에서 별도로 구현하고 있지는 않습니다.

`html` 명세에서 `title` 속성은 툴팁 같은 보조정보를 표현하는데 적절하다고 기술되어 있습니다.
https://www.w3.org/TR/html/dom.html#the-title-attribute
> The title attribute represents advisory information for the element, such as would be appropriate for a tooltip.

때문에 일반적으로 브라우저에서는 `title` 속성이 들어간 요소에 적절히 자체 툴팁을 노출합니다.
smarteditor2 에서는 툴바버튼에 이러한 브라우저 자체 툴팁 기능을 활용하고 있으며 브라우저마다 툴팁의 동작방식은 달라질 수 있습니다.
