### ISSUE TITLE
사진파일 업로드가 되지 않습니다.

### ISSUE THREAD

**Issue by hjs0902** [naver/smarteditor2#61]
콘솔창 로그가
path ::  D:/eGovFrameDev-2.7.1-32bit/workspace/ns_cm/src/main/webapp/upload/editorUpload
upfile : 넛쉘 스케쥴.png
targetFile : D:\eGovFrameDev-2.7.1-32bit\workspace\ns_cm\src\main\webapp\upload\editorUpload\2018_02_21_145817.png
moveFileName : 2018_02_21_145817.png
filename : 2018_02_21_145817.png
moveFileName : 2018_02_21_145817.png
path ::  D:/eGovFrameDev-2.7.1-32bit/workspace/ns_cm/src/main/webapp/upload/editorUpload
e : null

아래와 같이 나타납니다.
파일서버에 filename 으로 저장까지는 시키나, 콜백을 잘 못받아 오는 것 같습니다.
피들러를 이용하여 확인하여도, 콜백 시 정상적인 화면 주소가 아닌 null값으로 받아오는 걸 확인할 수 있습니다. 
기존까지는 잘 사용하였는데, 1월 초 부터 이상증상이 나타났습니다. (스마트에디터2, 익스플로러에서만)
이 증상에 대한 해결방법을 알고싶습니다.

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
