### ISSUE TITLE
외부 글 복사후 smart editor에 붙여넣기 했을때 HTML TAG 제거 관련

### ISSUE THREAD

**Issue by hij1127** [naver/smarteditor2#63]
외부 글 복사후 smart editor에 붙여넣기 했을때 HTML TAG 제거가 가능한가요?
글을 붙여넣고 editor 로 보면 괜찮은데 아래의 html 로 바꿔서 보면 tag가 전부 붙어있습니다. 
어디를 수정해야 tag를 없앨수 있는지 알고싶네요
smart editor 2.1 사용중입니다 .

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
