### ISSUE TITLE
양쪽배분을 기본값으로 하려면 어떻게 해야하나요?

### ISSUE THREAD

**Issue by carrog** [naver/smarteditor2#64]
문단정렬이 외쪽정렬이 기본인데요, 이 부분을 양쪽배분이 기본값이 되도록 설정하려고 합니다.
어느부분이 수정되어야할지 가이드 부탁드립니다.

**Comment by kyungilpark** [comment]
디폴트 정렬을 직접 지정하는 API는 없습니다. 
대신 편집영역의 기본 스타일을 다음과 같이 css로 조정하여 노출시킬 수 있습니다.
smart_editor2_inputarea_html5.html
smart_editor2_inputarea_ie8.html  
```html
<body class="se2_inputarea" style="height:0;-webkit-nbsp-mode:normal;text-align:justify"></body>
```
다만 최종 저장되는 html은 기본스타일이 없는 상태이므로 뷰어페이지에서도 동일하게 적용해주셔야 합니다.
