### ISSUE TITLE
스마트 에디터 csp를 지원하나요?

### ISSUE THREAD

**Issue by gkgk3442** [naver/smarteditor2#65]
spring security로 csp(Content Security Policy)를 적용하려고합니다.
항상 사용하던 ckeditor는 csp를 지원할 생각이 없는 것 같고...
혹시 네이버에디터는 csp를 지원하고 있는지 궁금합니다.

지원의 의미는 unsafe-inline 나 unsafe-eval 등을 사용하지 않고 'self' 혹은 한두개의 해쉬값만 사용해서 사용 가능한지 하는 것 입니다.

**Comment by kyungilpark** [comment]
현재 smarteditor2 에서 jindo 라이브러리를 사용하고 있습니다.
jindo 라이브러리 자체가 IE8 지원을 위해 eval 을 사용하고 있는 것으로 알고 있습니다.
라이브러리 디펜던시 때문에 현재로썬 지원이 불가능해보입니다.
