### ISSUE TITLE
하이퍼링크 target 설정 오류

### ISSUE THREAD

**Issue by kyus** [naver/smarteditor2#67]
http://naver.github.io/smarteditor2/user_guide/

소개 > 제공 기능 상세 > 하이퍼링크

설명란에는 링크 걸면 새창에서 뜬다고 되어 있는데,
실제 적용 해보면 target=_self 로 지정되어 현재창에서 오픈 되고 있습니다.

하이퍼링크시 새창에서 뜨지 않으면 불편한점이 여러모로 많습니다.

새창에서 뜨도록 기본 코드를 수정해 주세요.

**Comment by kyungilpark** [comment]
스펙상 `_self` 가 기본값이라 그대로 두고
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target
새창으로 열기(`_blank`)를 선택할 수 있는 기능 추가했습니다.
`v2.10.1` 에 반영될 예정입니다.
