### ISSUE TITLE
스마트에디터2.0 SSL 사이트 로딩 속도

### ISSUE THREAD

**Issue by woduddl** [naver/smarteditor2#68]
안녕하세요.
스마트에디터2.0(ver.2.8.2.3) 사용시 
SSL이 적용된 사이트의 경우 에디팅 툴이 로딩되는 속도가 현저히 느립니다.
로딩이 완료되는 시간은 3~10초 정도 사이입니다.
해당 문제에 대한 개선사항 또는 개발시 추가 적용 가능한 부분이 있는지 문의드립니다.
감사합니다.

**Comment by kyungilpark** [comment]
스마트에디터2 로딩속도는 SSL 적용과는 별 상관이 없습니다.
데모페이지에서도 HTTP 와 HTTPS 간에 로딩속도차이는 없습니다.
http://naver.github.io/smarteditor2/demo/ 
https://naver.github.io/smarteditor2/demo/ 

SSL 설정상의 문제가 아닌지 확인부탁드립니다.
혹은 적용된 사이트 알려주시면 좀 더 도움드릴 수 있을듯 합니다.

**Comment by woduddl** [comment]
답변 감사합니다.

**Comment by kyungilpark** [comment]
dns 등록되어있나요?
아예 접근이 안되는데요

**Comment by woduddl** [comment]
URL 보내드립니다.
https://harassment.ytn.co.kr/editorDemo.php
감사합니다.

**Comment by kyungilpark** [comment]
확인해봤는데 SSL 과 상관없이 minify 된 js 소스 다운로드가 너무 오래걸리네요.
아래 파일이 다운로드되는데 4초정도 걸립니다.
http://harassment.ytn.co.kr/editor/js/smarteditor2.min.js
아파치 설정을 최적화하셔야 할것 같습니다.
해당 파일은 341kb 밖에 안되게 때문에 네트웍 상황에 따라 다르지만 보통 100~200ms 정도면 다운로드됩니다.

**Comment by woduddl** [comment]
답변 감사합니다.
