### ISSUE TITLE
&gt;&lt; 표기오류

### ISSUE THREAD

**Issue by JONGHWALEE** [naver/smarteditor2#69]
데이터로 치환하여 데이터화는 되나 실제 데이터베이스 로딩이후 재표출시에는 사라집니다

1. 단순화살표로는 동작하나 <내용> 이렇게 사용할시 <내용> 모두가 사라지는 현상
2. <Server> 으로 입력시 데이터베이스에는 &lt;Server&gt; 으로 들어가나 DB에서 꺼내서 표출하면 &lt;Server&gt;&lt;/Server&gt;으로 치환되어 버립니다

**Comment by kyungilpark** [comment]
에디터에 `<Server>` 로 입력해서 저장하면 DB 에 `&lt;Server&gt;` 로 저장되어야 합니다.
DB에 `<Server>`로 치환되어 저장되었다면 WAS서버에서 필터링하고 있는게 아닌가 싶습니다.

**Comment by JONGHWALEE** [comment]
smarteditor2.min.js 파일을 부문적으로 console.log로 찍어보니 해당실행이후 바뀌는 것을 확인하였습니다

정리하면 서버에는  &lt;Server&gt; 으로 저장됨 (정상)
에디터를 위하여 서버에서 꺼낼때 <Server> 으로 치환 이후 <server></server> 으로 에디터에서 처리되나 해당 위치를 아직 찾기 못하였습니다. 한글내용이 들어갈경우 문제 없으나 영어가 들어갈경우 처리 됩니다

**Comment by kyungilpark** [comment]
`에디터를 위하여 서버에서 꺼낼때 <Server> 으로 치환` 한다는게 무슨 말씀인지 잘모르겠습니다.
HTML에서 꺽쇠가 표현되기 위해선 `&lt;Server&gt;` 형태로 내려와야 합니다.
`<Server>` 로 내려오게 되면 브라우저에서 태그로 인식하기 때문에 자동으로 `<Server></Server>` 로 변환됩니다.

**Comment by JONGHWALEE** [comment]
현재 상태 대로 정리해 보겠습니다 (그리고 감사드립니다)

1. 신규등록 : `<Server>`  
1-1. 데이터베이스 저장시 : `&lt;Server&gt;`
2. 수정모드  데이터베이스 로딩이후 단순 표출시 :  `&lt;Server&gt;`
2-1. 에디터 활성화시 :  `<server></server>`

위와 같이 데이터 흐름이 발생 합니다. 에디터에서 표출되려면  `&lt;Server&gt;`  값이 그대로 와야 하는데 변경이 되어 버립니다.

**Comment by kyungilpark** [comment]
아... `<textarea><p>&lt;Server&gt;</p></textarea>` 이렇게 되어있으면 `textarea.value`값이 `<p><Server></p>` 로 반환되는군요.. ㅠ.ㅠ
`&lt;` -> `&amp;lt;`, `&gt;` -> `&amp;gt;` 로 변환해서 넣어주어야 할것 같습니다.
https://stackoverflow.com/questions/3003375/how-to-show-lthtmlgt-in-textarea

**Comment by JONGHWALEE** [comment]
넵감사합니다 저도 종전에 네이버를 보고 코드를 확인했습니다....
당연히 될거라고 생각했는데 아쉽네요 ㅎㅎ
