### ISSUE TITLE
에디터 입력 후 저장시 첫 태그만 &lt; &gt; 로 자동변환되고 게시글에 태그 노출 됩니다 

### ISSUE THREAD

**Issue by lindsey0107** [naver/smarteditor2#70]
이상하게 에디터 입력 저장하면, 첫 글자 앞부분의 태그만  &lt; &gt;  로 자동변환됩니다.
예를들어 <p>555 가 있으면 &lt;p&gt;555 가 되는거지요.
다른 부분은 모두 변환되지 않습니다! 
그리고 첫 부분에 이렇게 변환되어 저장이 되면 게시글에 <p>가 그대로 노출됩니다.

관련 js 파일에
			var l_intro = $("#introduction").val();
			l_intro = l_intro.replace("<", "&lt;");
			l_intro = l_intro.replace(">", "&gt;");
해당부분은 있습니다만, 이건 < > 를 사용자가 입력시에 태그로 저장되지 않게 하기 위함이구요
다른 어떤부분도 자동 생성된 태그에 대하여 변환되지는 않고,
사용자가 < > 를 입력하면 그부분은 변환이 됩니다.

그런데 이부분에서 앞서 태그가 게시글 맨 앞에서 변환되면 태그 노출이 되는데,
중간에 사용자가 < > 를 입력하여 변환되는 경우는 태그 노출은 되지 않습니다..

어떠한 문제인지 조언부탁드립니다..

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
