### ISSUE TITLE
크롬에서 Blocked a frame with origin "null" from accessing a cross-origin frame. 오류발생

### ISSUE THREAD

**Issue by hanajun131** [naver/smarteditor2#72]
로컬에서 받은 소스로 실행해서 테스트하려고 하니 IE 11.48.17134.0 에서는 문제가 없으나
크롬 버전 66.0.3359.181(공식 빌드) (64비트)에서

Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (file:///C:/Users/manage/Downloads/smarteditor2-master/smarteditor2-master/workspace/js/service/HuskyEZCreator.js:82:37)

Uncaught iframe for WYSIWYG editing mode can't be initialized. Please check if the iframe document exists and is also accessable(cross-domain issues). 

오류가 발생합니다.

오류발생 코드위치는
HuskeyEZCreator.js :82
fCreator = elIFrame.contentWindow[fCreator] || elIFrame.contentWindow.createSEditor2;
입니다.

서버에 설치해서는 문제가 없는지도 한번 봐야겠네요.

**Comment by kyungilpark** [comment]
크롬에서는 로컬파일로 실행시키면 [Same-origin policy](https://developer.mozilla.org/ko/docs/Web/Security/Same-origin_policy) 때문에 브라우저자체에서 iframe 과 통신을 막아 동작하지 않습니다.
