### ISSUE TITLE
sms: 하이퍼 링크에 오작동 현상이 있는데, 이걸 누가 좀 바로 잡아줄 수 없겠는지요?

### ISSUE THREAD

**Issue by humansoft** [naver/smarteditor2#73]
수고 많습니다.
별도의 페이지에서는 sms:하이퍼 링크가 정상적으로 동작하는데, smarteditor2 를 편집기로 사용하는 게시판에다 동일한 소스를 저장하고 나서 소스 보기를 해보면 이상한 형태로 변형되어 저장되어 있음을 알 수 있고, 하이퍼링크가 작동하지 않습니다.

독립페이지에서 테스트해본 소스 코드 
<a href="tel:01012345678">010-1234-5678</a>로 전화 걸기~</span><br>
	<a href="sms:01012345678">010-1234-5678</a>로 문자 보내기~</span><br>

위의 소스를 게시판에 저장한 다음 소스보기를 해보면 아래와 같이 나타납니다.

    * 아래 소스를 살펴보면 sms: 링크 걸려야 할 부분이 이렇게 바뀌어 있음을 볼 수 있습니다.
          <a>010-3381-0218</a>로 문자 보내기~

        <div id="bo_v_con"><table width="100%" bgcolor="#f7ebdd" border="0" cellspacing="0" cellpadding="20"><tbody><tr><td height="30" align="center"><b><span style="font-size:16pt;">
		<a href="tel:01012345678">010-1234-5678</a>로 전화 걸기~</span></b></td>
	</tr><tr><td height="30" align="center"><b><span style="font-size:16pt;"><a>
		010-1234-5678</a>로 문자 보내기~</span></b></td>
	</tr></tbody></table></div>

**Comment by kyungilpark** [comment]
일단 기본적으로 smarteditor2 자체의 url 삽입기능에서 `tel:`,`sms:` 프로토콜을 지원하진 않습니다.
하지만 HTML 모드에서 직접 넣으셨다면 따로 유효성체크를 하지 않기 때문에 변경되지는 않을 건데요..
혹시 서버측에서 저장시 유효성체크하는건 아닌가요?
