### ISSUE TITLE
fCreator(elPlaceHolder, htParams); 오류

### ISSUE THREAD

**Issue by fvgtv** [naver/smarteditor2#74]
스마트 에디터 사용중에 fCreator(elPlaceHolder, htParams);오류와 함께 내용을 작성하는 칸 바로 아래부분이 404에러와 함께 실행이 되지않는데 어떤 조치를 취해야 하나요?

![image](https://user-images.githubusercontent.com/40972475/42428750-40f22934-8370-11e8-9b36-fc841d6cd575.png)

**Comment by kyungilpark** [comment]
스킨페이지에 `SE2BasicCreator.js` 파일이 제대로 로딩되었는지 확인부탁드립니다.

**Comment by fvgtv** [comment]
![image](https://user-images.githubusercontent.com/40972475/42497440-54044206-8464-11e8-8fee-805187c22721.png)

확인했는데 경로는 정상적으로 되있는거 같았습니다

**Comment by kyungilpark** [comment]
개발자도구의 에러마크로 봐선 해당 파일을 못찾는게 확실해보이는데요..
404 면 콘솔로그에 찍힐테니 해당 url 로 정말 접근이 되는지 확인해보셔야 할 것 같습니다.
WAS(톰캣등)로 띄우시고 정적리소스를 웹서버(아파치등)에 안 올리셨다거나(혹은 정적리소스를 jkmount 안해두셨다거나...) 확인해보시는게 좋을 듯 싶습니다.
