### ISSUE TITLE
SmartEditor Basic 2.0 사용시 IE Edge에서 스크립트 오류

### ISSUE THREAD

**Issue by rjy1537** [naver/smarteditor2#75]
스마트에디터 베이직 2.0 사용중입니다.

IE10 버젼까지는 정상적으로 되는데 IE Edge에서부터 스크립트 오류가 발생합니다.

개발자도구를 키고 내용영역을 클릭하면 아래와 같은 스크립트오류가 납니다.

SCRIPT5007: 정의되지 앉음 또는 null 참조인 'type' 속성을 가져올 수 없습니다.
파일 : loader-min.js, 줄 :1, 열 : 15748

버그 부분 확인해보니 아래와 같은 영역입니다.

this.isCollapsed=function(){this._oSelection=this._document.selection; return this._oSelection.type == "None"

에서 나고 있더라고요..

꼭 확인 부탁드립니다.

**Comment by kyungilpark** [comment]
음.. IE엣지를 구버전IE로 인식하고 있는것 같습니다.
스마트에디터2 혹은 jindo 라이브러리가 구버전이라서 IE엣지를 인식못하는것 같습니다.
스마트에디터2 상세버전과 사용하시는 jindo라이브러리 버전을 알 수 있을까요?

**Comment by rjy1537** [comment]
스마트에디터2 상세버전과 사용하시는 jindo라이브러리 버전은 어디서 확인해야 하나요?

**Comment by kyungilpark** [comment]
아... 2.1.2 버전이면 IE엣지가 나오기 이전 버전을 사용하고 계시네요...
IE엣지는 코드명 [스파르탄](https://en.wikipedia.org/wiki/Microsoft_Edge)이라는 이름으로 2015년7월에 처음 릴리즈되었습니다.
스마트에디터에서 IE엣지에 대해 대응한 버전은 [2.8.5](https://github.com/naver/smarteditor2/blob/master/CHANGELOG.md#285) 부터입니다.
가능하시다면 버전업을 권장드립니다.

**Comment by rjy1537** [comment]
네 답변 감사합니다.
버젼업 관련 url 알려주시면 감사하겠습니다~

**Comment by kyungilpark** [comment]
버전업가이드는 따로 없고 
https://github.com/naver/smarteditor2/releases 에서 zip 파일 내려받아서 dist 폴더내용으로 교체하시면 됩니다.
