### ISSUE TITLE
스마트에디터2 사용중인대요

### ISSUE THREAD

**Issue by leesunghul** [naver/smarteditor2#76]
안녕하세요 스마트에디터2 사용중인대요
html형식 내용을 editor형식으로 가지고올때 html 형식으로 가져올수있는 방법있을까요?
찾아봐도 없는거같아서 그렇습니다..
여기서 지금 막혀서요....

**Comment by kyungilpark** [comment]
어떤 데이터를 가져오고 싶으신건지 제가 질문내용을 이해를 못했는데요..
`oEditors.getById["ir1"].getIR()` 로 반환되는 데이터 말고 다른 데이터값을 원하시는건가요?
