### ISSUE TITLE
이미지 업로드시 엔터누르면 작은 박스가 나오고 업로드가 안되요

### ISSUE THREAD

**Issue by pureperson** [naver/smarteditor2#77]
이미지 업로드시 엔터누르면 작은 박스가 나오고 업로드가 안되요

그런데 모든 컴퓨터가 안되는게 아니고 대부분의 사용자가 정상적으로 업로드가 되는데

몇몇 사용자가 안된다고 합니다.

안되는 사용자들의 컴퓨터 환경을 물어보면 특별한게 없어요

익스플로러 버전이 낮은것도 아니고..

![sm](https://user-images.githubusercontent.com/41313927/42794365-e89d341e-896d-11e8-96d2-edb8cfc46e35.png)

이유가 뭘까요?

인터넷옵션 문제일까요..

**Comment by kyungilpark** [comment]
첨부해주신 스크린샷의 작은박스는 업로드시 임시로 생성되는 iframe인 것으로 보입니다.
원래는 업로드가 성공하거나 실패했을때 자동으로 제거되는데요..
제거되지 않았다는건 서버응답을 제대로 받지못하거나 스크립트오류가 발생했을 것으로 보입니다.
업로드시점에 서버로그를 확인하시거나 스크립트오류 확인해보셔야 원인파악이 가능할 듯합니다.

**Comment by pureperson** [comment]
해결했네요.
UTF8 문제였습니다. 한글명의 파일을 업로드 할때 에러 나는거였네요.
업로드시 파일명을 변경해서 해결했습니다.
