### ISSUE TITLE
익스플로러에서 스마트에디터2.0 입력창크기조절 어떻게해야하나요 ?

### ISSUE THREAD

**Issue by joonzzang** [naver/smarteditor2#79]
익스플로러에서 스마트에디터2.0 입력창 크기 조절할 때에 화면에 벗어나는 크기로 조절하면 스크롤바가 따라 내려올수는 없을까요 ?
화면에 벗어나는 만큼 마우스를 당기면 클릭 값이 계속 먹어서 스크롤 바를 움직일 시에 마우스를 따라 입력창 크기가 마음대로 바뀌는데 수정 할 수 있는 방법이 없을까요?

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
