### ISSUE TITLE
photo_uploader 플러그인에서 Content-Type에 boundary값이 붙지 않습니다

### ISSUE THREAD

**Issue by hayarobys** [naver/smarteditor2#81]
**환경**
SmartEditor 2.9.0 + 2.8.2.3의 photo_uploader
STS - Java/Spring/JSP
Chrome 67.0.3396.99

**현상**
HTML5지원 브라우저에서 이미지 업로드시 Content-Type이 application/x-www-form-urlencoded; charset=utf-8로 보내지는 현상을 발견했습니다. ([참조 이미지](https://i.imgur.com/cCnEuFW.png))
파일 전송은 multipart/form-data가 바람직하기에 Content-Type을 변경하고자 하는데 어디를 수정해야 하나요?

2.8.2.3의 데모 파일(/sample/photo_uploader/attach_photo.js)에 나온 아래 코드대로 컨텐츠 타입을 수동으로 넣을 경우 boundary값이 자동으로 붙지 않기에 사용 불가합니다. ([참조 이미지](https://i.imgur.com/dRSs992.png))
`oAjax.header("Content-Type","multipart/form-data");`

jindo.$Ajax에 아예 컨텐츠 타입 설정 기능이 없는 것인지요...
확인 부탁드립니다.

**Comment by kyungilpark** [comment]
`attach_photo.js` 소스 확인해보니 `jindo.$Ajax` 자체가 파일전송을 지원하지 않아서 패치한 것으로 보입니다.
```js
 	// 2012.05 현재] jindo.$Ajax.prototype.request에서 file과 form을 지원하지 안함. 
 	jindo.$Ajax.prototype.request = function(oData) {
```

D&D 방식이 필요없다면 ajax 방식으로 전송하지않고 form submit 으로 업로드되도록 다음과 같이 `bSupportDragAndDropAPI`변수값을 고정하셔서 사용하시기 바랍니다.
```js
	//File API 지원 여부로 결정
	function checkDragAndDropAPI(){
		bSupportDragAndDropAPI = false;
	}
```

D&D 방식이 필요하다면 boundary 값을 직접붙여서 전송하도록 패치하셔야 할 것 같습니다.
boundary 작성방법은 MDN 참고하시면 될 듯합니다.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Submitting_forms_and_uploading_files

**Comment by djjong77** [comment]
attach_photo.js 소스를 php에서 사용하면 정상적으로 되는데 java에서는 content-type파일을 아래와 같이 변경하면 됩니다. 

	if(!this._headers["Content-Type"]){
                                req.setRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=utf-8");
 			}

아래와 같이 변경하면 java, jsp에서도 정상적으로 처리가 됩니다. 브라우줘별로 특성이 있어서 file/unknown로 설정 했습니다.

	if(!this._headers["Content-Type"]){
 				req.setRequestHeader("Content-Type", "file/unknown; charset=utf-8");
 			}
