### ISSUE TITLE
네이버 스마트 에디터 사용중인데 질문입니다.

### ISSUE THREAD

**Issue by kkking23** [naver/smarteditor2#83]
네이버 스마트 에디터에서 텍스트(글자)는 가운데 정렬 또는 오른쪽 정렬 후 등록하면 정렬이 잘 됩니다

그런데 이미지 파일을 올린 후 가운데 또는 오른쪽 정렬을 하면 무조건 왼쪽 정렬로 고정이 되어 버리는데 혹시 해결방법이 있을까요?

**Comment by kyungilpark** [comment]
음... 잘 이해가 안되는데요..
에디터 화면에서 이미지 정렬이 안된다는건가요? 아니면 저장 후 뷰어 화면에서 안된다는건가요?

**Comment by kkking23** [comment]
저장후에 뷰어 화면에서 가운데 정렬이 안됩니다.
글씨는 되는데 이미지가 문제입니다

**Comment by kyungilpark** [comment]
그럼 뷰어화면의 css 를 확인해보셔야 할것 같습니다.

**Comment by kkking23** [comment]
혹시 css에 imageupload.css 파일에
1. #imageInfoBox {
    position: absolute;
	left: 548px;
}

2. .imageBox, .imageBoxHighlighted {
	width: 120px;
	height: 90px;
	margin: 3px 3px;
	float: left;
}

3. #insertionMarker img {
	float: left;
}

이렇게 3군데가 left가 있는데 어느부분인지 알려주실수 있으신가요?

**Comment by kyungilpark** [comment]
@kkking23 님
죄송합니다. 그냥 css 만 가지고는 유추할 수가 없습니다.
혹시 뷰어화면을 확인할 수 있는 url을 공개해주실 수 있다면 도움드릴 수 있을 듯 합니다.

**Comment by kkking23** [comment]
http://coin4rum.co.kr/Transaction_Board/board_list.asp?top_menu_no=&left_menu_no=19&menu_no=110
게시물에 1348번 글입니다.

**Comment by kyungilpark** [comment]
`reset.css` 가 잘못되어 있는듯합니다.
![2018-09-03 4 43 53](https://user-images.githubusercontent.com/483765/44973820-c3d1da80-af98-11e8-9f1e-9fe4b044e17b.png)
`img` 는 `inline`요소인데 강제로 `block`요소로 바꾸어놔서 `text-align:center` 가 적용되지 않고 있습니다.
보통은 `reset.css` 를 사용하더라고 `img` 의 `display`는 건드리지 않는데 `display:block` 으로 고정시키신 이유를 알아보시고 해당 스타일이 필요한 곳에만 한정적으로 사용하도록 수정하시는게 좋을듯합니다.

**Comment by kkking23** [comment]
좋은 답변 감사합니다
