### ISSUE TITLE
스마트에디터2 HTML 편집 모드에서 스타일 태그 사용가능 여부

### ISSUE THREAD

**Issue by lavinoys** [naver/smarteditor2#84]
안녕하세요.
스마트에디터2의 편집모드 중 HTML에서
<style> 태그를 입력하고 Editor 모드로 변경하면 <style>태그가 누락됩니다.
또한 <script>태그도 누락되는걸 확인했습니다.
해당 태그가 사라지는 이슈를 설정을 통하여 해결 할 수 있는것인지, 아니면 아예 <style>, <script>태그를 사용할 수 없는 것인지 알고싶습니다. 
css를 적용하기 위해선 인라인으로만 적용 가능할까요?

**Comment by kyungilpark** [comment]
https://github.com/naver/smarteditor2/issues/7#issuecomment-279275453 답변 참고바랍니다.

**Comment by lavinoys** [comment]
@kyungilpark 
해결됐습니다. 감사합니다.
