### ISSUE TITLE
스마트에디터2.0 라이선스 관련 문의

### ISSUE THREAD

**Issue by nobelbox** [naver/smarteditor2#88]
스마트에디터를 공공기관에스 운영하는 대국민 서비스에 적용할 수 있는지 문의드립니다.
커스터마이징 없이 에디터 기능만 사용할 예정이며, 공공기관 서비스에 사용시 라이선스 위배가 되는지 문의드립니다.
상업적 목적은 아니며 정보 교류용 목적으로 사용하고자 합니다.

**Comment by kyungilpark** [comment]
https://github.com/naver/smarteditor2/issues/59#issuecomment-403799832 참고바랍니다.
