### ISSUE TITLE
smart에디터에서 이미지 업로드시 access token을 해더에 넣어서 보내는 방법

### ISSUE THREAD

**Issue by life-jin** [naver/smarteditor2#89]
oauth2를 사용하여 웹사이트를 구현하고 있습니다.
글작성시에도 access token을 해더에 담아 보내고 있는데요
이미지 업로드시 access token을 해더에 담아 보낸는 방법이 있는지 궁금합니다.

jindo.$Ajax.prototype.request에서 구현하면 될 것으로 보이는데 맞나요?

**Comment by kyungilpark** [comment]
음... `jindo.$Ajax.prototype.request` 를 굳이 몽키패치하지 않아도 헤더값을 넣어 호출은 가능합니다.
```js
var ajax = jindo.$Ajax("http://www.remote.com",  options);
ajax.header("token", "blahblah" );
ajax.request();
```
진도 사용방법은 진도홈페이지 참고부탁드립니다.
https://github.com/naver/jindojs-jindo
http://jindo.dev.naver.com/docs/jindo/latest/desktop/ko/classes/jindo.$Ajax.html#method_header
