### ISSUE TITLE
스마트에디터 적용 하려고 하는데요.

### ISSUE THREAD

**Issue by realmon** [naver/smarteditor2#9]
검색해서 나오는 이전 링크 들이 죄다 네이버개발자 센터 메인으로만 넘어 가네요.
사용자 가이드 보고 얼추 기본 처리는 했는데요.
본문 이미지 처리 부분 소스가 없어서요.
해당 부분 내용 확인 좀 부탁 드립니다.

**Comment by kyungilpark** [comment]
기존 네이버개발자센터 저장소가 폐쇄되어 github으로 옮겨온지 얼마 안되었습니다.
저도 검색으로는 찾아오기 힘드네요. ㅠ.ㅠ

이미지 업로드 샘플은 서버쪽과 연동이 필요하다보니 단순한 예제 샘플임에도 마치 스마트에디터2 자체가 보안문제가 많은 것처럼 오도되는 경향이 있어서 2.9.0버전부터 소스저장소에서 제외되었습니다.

기존 샘플을 참고하고 싶으시면 [이전버전](https://github.com/naver/smarteditor2/releases/tag/v2.8.2.3)을 다운받아 `sample`폴더 참고하시길 바랍니다.

**Comment by taekwang1123** [comment]
dsfa
