### ISSUE TITLE
네이버 스마트 에디터 질문있습니다.

### ISSUE THREAD

**Issue by kkking23** [naver/smarteditor2#90]
내용에서 글부분과 사진첨부를 하여 등록을 했는데 글과 글사이 그리고 사진사이에도 엔터키를 계속눌러 줄 사이에 공백을 띄우게끔 하고 등록했습니다. 그런데 등록후 글을 보면 공백이 나타나지 않고 모두 바로 다음줄에 글이 위치해 있어 줄바꿈이 되지 않고 있습니다.(shift키 + 엔터키를 눌러야 줄바꿈이 간신히 됩니다) 혹시 방법이 없을지 궁금합니다 (아래에 문제의 게시글 링크 작성했습니다)

http://coin4rum.co.kr/Porami_Playground/board_list.asp?top_menu_no=&left_menu_no=&menu_no=32
- 1463번 게시물입니다. -

두번째로 내용에서 인터넷 URL을 www.naver.com만 쓰고 등록하려면 하이퍼링크가 안걸리고 끝부분에 엔터키를 치거나 끝부분에 스페이스바를 쳐야만 하이퍼링크가 걸리는데 이게 원래 그런건가요?

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
