### ISSUE TITLE
글쓰기 후 html 클릭해서 소스를 보면.

### ISSUE THREAD

**Issue by freemaster** [naver/smarteditor2#92]
글쓰기를 하다가 html을 눌러서 현재 소스를 보게 되면
개행이 없어 모두 한줄로 연결이 되어 있습니다.
예) 
동해물과 백두산이 마르고 닳도록 
하나님이 보우하사 우리나라 만세
무궁화 삼천리 화려강산
대한사람 대한으로 길이 보존하세
Editor 상태에서 등록을 하고 HTML상태로 들어가서 확인을 해보면
개행이 되지 않고 p태그를 포함해서 모두 한줄로 저장이 되어집니다.
**(태그가 화면에 표시되지 않아 <>를 []로 변경하였습니다.)**
[p style="box-sizing: border-box; word-break: break-all; background-color: rgb(255, 255, 255);"][span style="font-family: &quot;Malgun Gothic&quot;, dotum, sans-serif;"]동해물과 백두산이 마르고 닳도록&nbsp;</span][/p][p style="box-sizing: border-box; word-break: break-all; background-color: rgb(255, 255, 255);"][span style="font-family: &quot;Malgun Gothic&quot;, dotum, sans-serif;"]하나님이 보우하사 우리나라 만세</span][/p][p style="box-sizing: border-box; word-break: break-all; background-color: rgb(255, 255, 255);"][span style="font-family: &quot;Malgun Gothic&quot;, dotum, sans-serif;"]무궁화 삼천리 화려강산</span][/p][p style="box-sizing: border-box; word-break: break-all; background-color: rgb(255, 255, 255);"][span style="font-family: &quot;Malgun Gothic&quot;, dotum, sans-serif;"]대한사람 대한으로 길이 보존하세</span][/p]
이부분을 개행이 되서 저장이 되게 수정할 수 있나요?
[p]동해물과 백두산이 마르고 닳도록[/p]
[p]하나님이 보우하사 우리나라 만세[/p]
[p]무궁화 삼천리 화려강산[/p]
[p]대한사람 대한으로 길이 보존하세[/p]
이러한 형태로 개행이 되어지게 변경할 수 있을까요??

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
