### ISSUE TITLE
에디터인 iframe 내에 있는 사용자 툴바(toolbar)를 iframe 외부에서 제어하고 싶습니다.

### ISSUE THREAD

**Issue by shlee-kor** [naver/smarteditor2#94]
사용자 툴바(toolbar)를 추가(id 등은 부여)하고, 아래 옵션값을 이용해서 사용자 툴바(toolbar)를 선택하여
보여주거나 숨기고 싶습니다.
nhn.husky.EZCreator.createInIFrame({옵션값})

매뉴얼을 찾아봐도 툴바(toolbar)를 제어하는 기능은 없더군요.
oAppRef 레퍼런스의 getById를 이용해서 이러한 제어가 가능한가요?

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
