### ISSUE TITLE
iframe을 가져오는데 cross-origin 이슈가 있습니다.

### ISSUE THREAD

**Issue by BangShinChul** [naver/smarteditor2#95]
안녕하세요. 
현재 스마트에디터 오픈소스를 사용하여 테스트하는 중에 HuskyEZCreator.js 의

`
fCreator = elIFrame.contentWindow[fCreator] || elIFrame.contentWindow.createSEditor2;
`

부분에서 
`
Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous>
`
라는 에러가 발생합니다.

혹시나 ellFrame.contentWindow[fCreator] 나 ellFrame.contentWindow.createSEditor2 의 값이 null이 아닐까 생각이 들어 디버깅해봤지만 모두 값은 정상적으로 박혀있었습니다. 하지만 계속 null 이라는 에러가 뜨는데요..

혹시 이 에러의 원인을 알 수 있을까요??

**Comment by kyungilpark** [comment]
로컬파일로 띄우셔서 그런것 같습니다. #72 참고
서버위에서 띄워보시기 바랍니다.
