### ISSUE TITLE
스마트 에디터 초기 오류 문의드립니다.

### ISSUE THREAD

**Issue by kyeongtak2** [naver/smarteditor2#96]
스마트 에디터 관련하여 한가지 문의 드립니다.
현재 HuskyEZCreator, SmartEditor2Skin.html 을 사용 하여
textarea 에 삽입은 하였는데, 기존 textarea 는 display:none; 처리 되며,
코드 상 바로 아래 iframe 으로 삽입 되는것을 확인 했습니다.

하지만 iframe 자체에 width:100%; height:0; 으로 잡혀서 표시가 안되고 있는 상황입니다.
textarea에 height를 지정해도 iframe에 적용이 안되고 있어, 관련하여

nhn.husky.EZCreator.createInIFrame({}); 에서 접근 가능한 방법이 있는지 문의 드립니다.

**Comment by kyungilpark** [comment]
오래된 질문 정리합니다.
