### ISSUE TITLE
스마트에디터 pre 태그 관련해서 문의 드립니다.

### ISSUE THREAD

**Issue by mineactor** [naver/smarteditor2#97]
다른 에디터에서 게시글을 카피하여 복사한 후
전체 내용에 대하여 pre태그를 적용하였는데..
작성완료를 누르면, pre태그가 내용 맨 앞으로
이동합니다.
<pre></pre>... 생략
전체 내용에 대하여 pre태그 적용하려면 어떻게
해야 하나요?

**Comment by kyungilpark** [comment]
1. 우선 "작성완료"시 서버로 전송되기전에 html 데이터가 깨지는건지 확인 부탁드립니다.
2. 만약 에디터에서 html 데이터가 깨지는 것이라면 붙여넣기된 html 자체가 깨져있을 가능성이 있습니다. IE 하위버전에서 종종 태그가 깨진채로 붙여넣어지는 경우가 있을때도 있습니다.

재현되는 브라우저와 html 데이터를 알려주시면 원인파악에 도움을 드릴 수 있을 듯합니다.
