### ISSUE TITLE
스마트에디터 2.0 줄바꿈 및 텍스트 스타일 관련 문의입니다.

### ISSUE THREAD

**Issue by sbj8492** [naver/smarteditor2#98]
현재 시스템 게시글 작성을 스마트에디터 2.0을 통해서 운영하고 있는데

기본 줄바꿈처리를 br태그로 해달라는 요청이 있어서 해당부분을 적용했는데

익스플로러에서 줄바꿈이나 색상등 스타일을 입히면 커서가 위치한 한줄 또는 선택한 블록만 스타일이 입혀지는게 아니라 전체가 적용이 되어버리네요.

크롬같은 경우에는 해당부분만 스타일 적용하면 div태그가 입혀져서 그 부분에 스타일 적용되는데 이것을 익스플로러에도 적용할 수 있을까요?

**Comment by kyungilpark** [comment]
SE2 최신버전, IE11 환경에서는 재현되지 않는데요.
사용하시는 SE2 버전과 오작동하는 IE 버전 알려주시면 확인해보도록 하겠습니다.
